// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/appset`
 * Purpose: Pin `renderNodeAppset` + `insertAppsetKustomization` to byte-exact cases mirroring
 *   `scripts/ci/render-node-appset.sh` (template sed-substitution + the WHOLE per-env
 *   appsets/<env>/kustomization.yaml render_kustomization output).
 * Scope: Pure unit tests — goldens mirror the shell renderer's output so the operator's emit can't skew
 *   against the `pnpm gen:node-appset --check` drift gate.
 * Invariants: BYTE_EXACT_WITH_RENDERER — token substitution + env-major/node-sorted whole-file ordering.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/appset, scripts/ci/render-node-appset.sh
 * @public
 */

import { describe, expect, it } from "vitest";

import {
  insertAppsetKustomization,
  removeFromAppsetsKustomization,
  renderNodeAppset,
} from "./appset";

// Minimal template carrying both tokens + an Argo goTemplate marker that must survive untouched.
const TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        revision: deploy/__ENV__-__NODE__
        files:
          - path: "infra/catalog/__NODE__.yaml"
  template:
    metadata:
      name: "__ENV__-{{.name}}"
`;

// The GENERATED per-env appsets/<env>/kustomization.yaml header — byte-exact to render-node-appset.sh's
// per-env render_kustomization heredoc (everything up to and including `resources:`).
const HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../control-plane/<env>/<env>-appsets-application.yaml).
# One AppSet per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

// A whole candidate-a appsets/candidate-a/kustomization.yaml listing canary/node-template/operator.
// Each per-env kustomization is self-contained (only ITS env's nodes); the full <env>- filename prefix
// is kept on disk even though the file is nested under <env>/.
const BEFORE = `${HEADER}
  - candidate-a-canary-applicationset.yaml
  - candidate-a-node-template-applicationset.yaml
  - candidate-a-operator-applicationset.yaml
`;

// Template carrying __REPO_URL__ on both the git generator and the Application source, mirroring
// scripts/ci/node-applicationset.yaml.tmpl — the byte-for-byte shared file (bug.5235).
const REPO_URL_TEMPLATE = `spec:
  generators:
    - git:
        repoURL: __REPO_URL__
        revision: deploy/__ENV__-__NODE__
  template:
    spec:
      source:
        repoURL: __REPO_URL__
        targetRevision: "deploy/__ENV__-{{.name}}"
`;

describe("renderNodeAppset", () => {
  it("substitutes __ENV__/__NODE__ globally and leaves {{.name}} intact", () => {
    expect(renderNodeAppset(TEMPLATE, "foo", "candidate-a")).toBe(
      `metadata:
  name: cogni-candidate-a-foo
spec:
  generators:
    - git:
        revision: deploy/candidate-a-foo
        files:
          - path: "infra/catalog/foo.yaml"
  template:
    metadata:
      name: "candidate-a-{{.name}}"
`
    );
  });

  it("defaults __REPO_URL__ to the canonical cogni-dao fleet host (byte-identical committed AppSet)", () => {
    expect(renderNodeAppset(REPO_URL_TEMPLATE, "foo", "candidate-a")).toBe(
      `spec:
  generators:
    - git:
        repoURL: https://github.com/cogni-dao/cogni.git
        revision: deploy/candidate-a-foo
  template:
    spec:
      source:
        repoURL: https://github.com/cogni-dao/cogni.git
        targetRevision: "deploy/candidate-a-{{.name}}"
`
    );
  });

  it("substitutes __REPO_URL__ with an isolated fleet's hosting repo on every occurrence (bug.5235)", () => {
    expect(
      renderNodeAppset(
        REPO_URL_TEMPLATE,
        "spawny-boi",
        "candidate-a",
        "https://github.com/cogni-test-org/cogni.git"
      )
    ).toBe(
      `spec:
  generators:
    - git:
        repoURL: https://github.com/cogni-test-org/cogni.git
        revision: deploy/candidate-a-spawny-boi
  template:
    spec:
      source:
        repoURL: https://github.com/cogni-test-org/cogni.git
        targetRevision: "deploy/candidate-a-{{.name}}"
`
    );
  });
});

describe("insertAppsetKustomization", () => {
  it("folds the new slug into the env's resources in ASCII-sorted position, re-rendering the whole file", () => {
    // 'foo' sorts between 'canary' and 'node-template' in candidate-a's node-set.
    expect(insertAppsetKustomization(BEFORE, "foo", "candidate-a")).toBe(
      `${HEADER}
  - candidate-a-canary-applicationset.yaml
  - candidate-a-foo-applicationset.yaml
  - candidate-a-node-template-applicationset.yaml
  - candidate-a-operator-applicationset.yaml
`
    );
  });

  it("is idempotent when the slug is already listed", () => {
    const once = insertAppsetKustomization(BEFORE, "foo", "candidate-a");
    expect(insertAppsetKustomization(once, "foo", "candidate-a")).toBe(once);
  });

  it("throws when the resources list is missing", () => {
    expect(() =>
      insertAppsetKustomization("kind: Kustomization\n", "foo", "candidate-a")
    ).toThrow(/resources/);
  });

  // CRITICAL regression (bug.5204/story.5039): a CONTROL env's dir holds FOREIGN workload envs'
  // AppSets (an akash node's non-production lane is reconciled by production). The old single-env
  // filename filter silently DROPPED those lines on every whole-file rewrite.
  it("preserves foreign-env lines when rewriting the production control kustomization", () => {
    const PRODUCTION_BEFORE = `${HEADER}
  - candidate-a-poly-applicationset.yaml
  - preview-poly-applicationset.yaml
  - production-beacon-applicationset.yaml
  - production-operator-applicationset.yaml
`;
    expect(
      insertAppsetKustomization(PRODUCTION_BEFORE, "newnode", "production")
    ).toBe(
      `${HEADER}
  - candidate-a-poly-applicationset.yaml
  - preview-poly-applicationset.yaml
  - production-beacon-applicationset.yaml
  - production-newnode-applicationset.yaml
  - production-operator-applicationset.yaml
`
    );
    // Folding a foreign-env pair in keeps env-major then node-sorted order (stated explicitly,
    // not the ASCII coincidence).
    expect(
      insertAppsetKustomization(PRODUCTION_BEFORE, "atlas", "preview")
    ).toBe(
      `${HEADER}
  - candidate-a-poly-applicationset.yaml
  - preview-atlas-applicationset.yaml
  - preview-poly-applicationset.yaml
  - production-beacon-applicationset.yaml
  - production-operator-applicationset.yaml
`
    );
  });

  it("is pair-scoped: the same slug may hold several workload envs in one control dir", () => {
    const WITH_CAND = `${HEADER}
  - candidate-a-poly-applicationset.yaml
  - production-poly-applicationset.yaml
`;
    // (candidate-a, poly) present does NOT make (preview, poly) idempotent.
    expect(insertAppsetKustomization(WITH_CAND, "poly", "preview")).toBe(
      `${HEADER}
  - candidate-a-poly-applicationset.yaml
  - preview-poly-applicationset.yaml
  - production-poly-applicationset.yaml
`
    );
  });

  it("THROWS on an unparseable resource line instead of silently dropping it", () => {
    const MANGLED = `${HEADER}
  - candidate-a-poly-applicationset.yaml
  - some-random-file.yaml
`;
    expect(() =>
      insertAppsetKustomization(MANGLED, "foo", "candidate-a")
    ).toThrow(/unparseable resource line/);
    expect(() =>
      removeFromAppsetsKustomization(MANGLED, "poly", "candidate-a")
    ).toThrow(/unparseable resource line/);
  });

  // PER-ENV (story.5020) — each env's kustomization is self-contained, so folding a
  // slug into one env never touches another env's file. A node born into a subset of
  // envs simply has insertAppsetKustomization called once per birth env on that env's
  // own file; an env it was NOT born into is never passed here, so it stays untouched.
  it("folds into preview's own (smaller) node-set independently of candidate-a", () => {
    const PREVIEW_BEFORE = `${HEADER}
  - preview-operator-applicationset.yaml
`;
    expect(insertAppsetKustomization(PREVIEW_BEFORE, "foo", "preview")).toBe(
      `${HEADER}
  - preview-foo-applicationset.yaml
  - preview-operator-applicationset.yaml
`
    );
  });
});

describe("removeFromAppsetsKustomization", () => {
  // The decommission inverse re-renders the WHOLE file over the reduced node-set, so its output is
  // byte-exact to render-node-appset.sh on the reduced catalog (story.5020). A node listed between
  // 'canary' and 'node-template' is dropped, leaving the surrounding entries untouched + node-sorted.
  const WITH_FOO = `${HEADER}
  - candidate-a-canary-applicationset.yaml
  - candidate-a-foo-applicationset.yaml
  - candidate-a-node-template-applicationset.yaml
  - candidate-a-operator-applicationset.yaml
`;

  it("drops the slug and re-renders the whole file node-sorted", () => {
    expect(removeFromAppsetsKustomization(WITH_FOO, "foo", "candidate-a")).toBe(
      BEFORE
    );
  });

  it("round-trips with insertAppsetKustomization (byte-identity on add→remove)", () => {
    const added = insertAppsetKustomization(BEFORE, "foo", "candidate-a");
    expect(removeFromAppsetsKustomization(added, "foo", "candidate-a")).toBe(
      BEFORE
    );
  });

  it("is idempotent when the slug is not listed", () => {
    expect(
      removeFromAppsetsKustomization(BEFORE, "absent", "candidate-a")
    ).toBe(BEFORE);
  });

  it("can empty an env's resources list down to the bare header", () => {
    const SINGLETON = `${HEADER}
  - candidate-a-onlynode-applicationset.yaml
`;
    expect(
      removeFromAppsetsKustomization(SINGLETON, "onlynode", "candidate-a")
    ).toBe(`${HEADER}\n`);
  });

  it("throws when the resources list is missing", () => {
    expect(() =>
      removeFromAppsetsKustomization(
        "kind: Kustomization\n",
        "foo",
        "candidate-a"
      )
    ).toThrow(/resources/);
  });
});
