// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2026 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/env-membership-plan`
 * Purpose: Pin the pure env-delta planner — add-env inserts, remove-env sha:null deletions +
 *   regenerated kustomization, and the ATOMIC_PER_ENV + idempotency invariants. Every env is an
 *   independent toggle while the non-empty deploy set and singleton activity authority remain valid.
 * Scope: Pure unit tests over hand-built control-plane fixtures (no Octokit).
 * Invariants: ATOMIC_PER_ENV, IDEMPOTENT, DELETE_VIA_SHA_NULL, TEMPLATE_OVERLAY_IS_RENDER_SOURCE,
 *   OPERATOR_SELF_HOSTS_THE_VERB.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/env-membership-plan
 * @public
 */

import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";

import {
  appsetPath,
  appsetsKustomizationPath,
  buildEnvDeltaPlan,
  buildPlacementPlan,
  CATALOG_PATH,
  type EnvDeltaResult,
  type EnvPlanCurrent,
  EnvPlanError,
  type EnvPlanOp,
  externalSecretPath,
  overlayPath,
  planEnvAddShape,
  schedulerEndpointPatchPath,
} from "./env-membership-plan";

const SLUG = "blue";

const KUST_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../<env>-appsets-application.yaml). One AppSet
# per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

const kustWith = (env: string, nodes: readonly string[]): string =>
  `${KUST_HEADER}\n${nodes
    .map((n) => `  - ${env}-${n}-applicationset.yaml`)
    .join("\n")}\n`;

// node-template overlay carrying the node-at-root migrate command renderOverlay requires.
const TEMPLATE_OVERLAY = `namespace: cogni-candidate-a-node-template
resources:
  - ../../../base/node-app
patches:
  - target: { kind: Service }
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30200
images:
  - name: node-app
    newName: ghcr.io/cogni-dao/cogni-template-node-template
initContainers:
  migrate: exec node /app/app/migrate.mjs /app/app/migrations
`;

// node-template overlay's external-secret.yaml (the ESO producer). renderOverlayFile only
// slug/port-renames it — node-template → blue everywhere, no migrate guard.
const TEMPLATE_EXTERNAL_SECRET = `apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  labels:
    app.kubernetes.io/component: node-template
spec:
  target:
    name: node-template-env-secrets
  dataFrom:
    - extract:
        key: candidate-a/node-template
`;

const APPSET_TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        files:
          - path: "infra/catalog/__NODE__.yaml"
`;

// Fixture node_id (REPO_SPEC_IS_IDENTITY_SSOT) — the UUID alias buildSchedulerEndpointOp asserts
// against the scheduler patch's existing entry (bug.5094 twin at the placement lever).
const NODE_ID = "11111111-1111-4111-8111-111111111111";

const catalogWith = (envs: readonly string[]): string =>
  `name: ${SLUG}
type: node
port: 3200
node_port: 31100
dockerfile: nodes/${SLUG}/app/Dockerfile
image_tag_suffix: "-${SLUG}"
migrator_tag_suffix: "-${SLUG}-migrate"
candidate_a_branch: deploy/candidate-a-${SLUG}
preview_branch: deploy/preview-${SLUG}
production_branch: deploy/production-${SLUG}
envs: [${envs.join(", ")}]
activity_env: ${envs[0] ?? "candidate-a"}
path_prefix: nodes/${SLUG}/
node_id: ${NODE_ID}
`;

// A bare scheduler-worker node-endpoints patch fixture carrying just SLUG's own pair — the shape
// `updateSchedulerEndpointHost` reads/rewrites. `url` is the routed address BEFORE a placement flip.
const schedulerPatchFixture = (url: string): string =>
  `apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-worker-config
data:
  COGNI_NODE_ENDPOINTS: "${SLUG}=${url},${NODE_ID}=${url}"
`;

function baseCurrent(envs: readonly string[]): EnvPlanCurrent {
  const appsetsKustomizationByEnv: Record<string, string> = {};
  const templateOverlayByEnv: Record<string, string> = {};
  const templateExternalSecretByEnv: Record<string, string> = {};
  const schedulerEndpointPatchByEnv: Record<string, string> = {};
  for (const e of envs) {
    appsetsKustomizationByEnv[e] = kustWith(e, ["blue", "operator"]);
    templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
    templateExternalSecretByEnv[e] = TEMPLATE_EXTERNAL_SECRET;
    schedulerEndpointPatchByEnv[e] = schedulerPatchFixture(
      `http://${SLUG}-node-app:3000`
    );
  }
  // preview is an env we ADD in tests, so make its template overlay + kustomization available.
  appsetsKustomizationByEnv.preview ??= kustWith("preview", ["operator"]);
  templateOverlayByEnv.preview ??= TEMPLATE_OVERLAY;
  templateExternalSecretByEnv.preview ??= TEMPLATE_EXTERNAL_SECRET;
  schedulerEndpointPatchByEnv.preview ??= schedulerPatchFixture(
    `http://${SLUG}-node-app:3000`
  );
  return {
    catalog: catalogWith(envs),
    templateOverlayByEnv,
    templateExternalSecretByEnv,
    appsetTemplate: APPSET_TEMPLATE,
    appsetsKustomizationByEnv,
    port: 3200,
    nodePort: 31100,
    schedulerEndpointPatchByEnv,
  };
}

const paths = (ops: readonly EnvPlanOp[]): string[] => ops.map((o) => o.path);
const deletes = (ops: readonly EnvPlanOp[]): string[] =>
  ops.filter((o) => o.op === "delete").map((o) => o.path);

describe("buildEnvDeltaPlan — ADD env", () => {
  it("inserts catalog edit + overlay + appset + kustomization fold for the added env", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // No deletes on an add.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("preview", SLUG),
        externalSecretPath("preview", SLUG),
        appsetPath("preview", "preview", SLUG),
        appsetsKustomizationPath("preview"),
      ].sort()
    );
    // ESO producer is cloned with the slug rename applied.
    const esOp = res.ops.find(
      (o) => o.path === externalSecretPath("preview", SLUG)
    );
    expect(esOp?.op).toBe("upsert");
    if (esOp?.op === "upsert") {
      expect(esOp.content).toContain("name: blue-env-secrets");
      expect(esOp.content).not.toContain("node-template");
    }

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    // Overlay rename applied (node-template → blue).
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("preview", SLUG)
    );
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toContain("cogni-candidate-a-blue");
    }
    // appsets kustomization now lists blue under preview.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain("preview-blue-applicationset.yaml");
    }
  });

  it("is idempotent when the env is already present", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — REMOVE env (partial)", () => {
  it("drops the env line + sha:null deletes overlay+appset + regenerates kustomization", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // Overlay + appset are DELETED (sha:null in the adapter).
    expect(deletes(res.ops).sort()).toEqual(
      [
        overlayPath("production", SLUG),
        externalSecretPath("production", SLUG),
        appsetPath("production", "production", SLUG),
      ].sort()
    );
    // Catalog edited + kustomization regenerated without blue.
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "production-blue-applicationset.yaml"
      );
    }
    // The catalog row itself is NEVER deleted on a remove (per-node state stays).
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
  });

  it("is idempotent when the env is already absent", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — safe removals", () => {
  it("rejects removing the current activity authority even when other deployments survive", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });

    expect(call).toThrowError(
      expect.objectContaining({
        code: "activity_authority_cutover_required",
        status: 422,
      })
    );
  });

  it("rejects removing the LAST remaining environment", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a"]),
      });

    expect(call).toThrowError(
      expect.objectContaining({
        code: "final_environment_required",
        status: 422,
      })
    );
  });

  it("is idempotent both directions on candidate-a (add already-present / remove already-absent)", () => {
    // add candidate-a when already present → no_changes
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: true,
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
    // remove candidate-a when already absent → no_changes (no authority mutation is attempted)
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["preview"]),
      }).kind
    ).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — TEMPLATE_OVERLAY_IS_RENDER_SOURCE", () => {
  // node-template's real catalog row: template port literals (3200/30200), production authority.
  const templateCatalogWith = (envs: readonly string[]): string =>
    `name: node-template
type: node
port: 3200
node_port: 30200
dockerfile: nodes/node-template/app/Dockerfile
envs: [${envs.join(", ")}]
activity_env: production
path_prefix: nodes/node-template/
`;

  const templateCurrent = (envs: readonly string[]): EnvPlanCurrent => {
    const appsetsKustomizationByEnv: Record<string, string> = {};
    const templateOverlayByEnv: Record<string, string> = {};
    const templateExternalSecretByEnv: Record<string, string> = {};
    for (const e of ["candidate-a", "preview", "production"]) {
      appsetsKustomizationByEnv[e] = kustWith(e, [
        "blue",
        "node-template",
        "operator",
      ]);
      templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
      templateExternalSecretByEnv[e] = TEMPLATE_EXTERNAL_SECRET;
    }
    return {
      catalog: templateCatalogWith(envs),
      templateOverlayByEnv,
      templateExternalSecretByEnv,
      appsetTemplate: APPSET_TEMPLATE,
      appsetsKustomizationByEnv,
      port: 3200,
      nodePort: 30200,
    };
  };

  it("removes node-template's DEPLOYMENT but keeps its overlay files (the render template)", () => {
    const res = buildEnvDeltaPlan({
      slug: "node-template",
      env: "candidate-a",
      present: false,
      current: templateCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["preview", "production"]);
    // REDUCED delete set: ONLY the appset leaves git.
    expect(deletes(res.ops)).toEqual([
      appsetPath("candidate-a", "candidate-a", "node-template"),
    ]);
    // The overlay files are NOT touched at all (no delete, no upsert).
    expect(paths(res.ops)).not.toContain(
      overlayPath("candidate-a", "node-template")
    );
    expect(paths(res.ops)).not.toContain(
      externalSecretPath("candidate-a", "node-template")
    );
    // Catalog env dropped + kustomization regenerated without node-template.
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [preview, production]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("candidate-a")
    );
    expect(kustOp?.op).toBe("upsert");
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "candidate-a-node-template-applicationset.yaml"
      );
      expect(kustOp.content).toContain("candidate-a-blue-applicationset.yaml");
    }
  });

  it("still refuses to remove node-template's activity authority (production)", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: "node-template",
        env: "production",
        present: false,
        current: templateCurrent(["candidate-a", "preview", "production"]),
      });
    expect(call).toThrowError(
      expect.objectContaining({
        code: "activity_authority_cutover_required",
        status: 422,
      })
    );
  });

  it("re-adds node-template as an ordinary add (overlay files already in tree are the source)", () => {
    const res = buildEnvDeltaPlan({
      slug: "node-template",
      env: "candidate-a",
      present: true,
      current: templateCurrent(["preview", "production"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview", "production"]);
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH("node-template"),
        overlayPath("candidate-a", "node-template"),
        externalSecretPath("candidate-a", "node-template"),
        appsetPath("candidate-a", "candidate-a", "node-template"),
        appsetsKustomizationPath("candidate-a"),
      ].sort()
    );
    // Rendering the template with its own slug + its own port literals is the identity
    // transform — the re-added overlay is byte-identical to the render source.
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("candidate-a", "node-template")
    );
    expect(overlayOp?.op).toBe("upsert");
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toBe(TEMPLATE_OVERLAY);
    }
    // Authority stays production (max of nextEnvs) — the add cannot demote it.
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("activity_env: production");
    }
  });

  it("is idempotent adding node-template to an env it already claims", () => {
    expect(
      buildEnvDeltaPlan({
        slug: "node-template",
        env: "candidate-a",
        present: true,
        current: templateCurrent(["candidate-a", "preview", "production"]),
      }).kind
    ).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — OPERATOR_SELF_HOSTS_THE_VERB", () => {
  it("refuses to remove operator from any env (the control plane cannot undeploy itself)", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: "operator",
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });
    expect(call).toThrow(EnvPlanError);
    try {
      call();
      throw new Error("expected EnvPlanError");
    } catch (e) {
      expect(e).toBeInstanceOf(EnvPlanError);
      expect((e as EnvPlanError).code).toBe("operator_node_immutable");
      expect((e as EnvPlanError).status).toBe(422);
    }
  });
});

describe("ACTIVITY_FOLLOWS_INGEST (bug.5079)", () => {
  const catalogOf = (plan: EnvDeltaResult): string => {
    if (!("ops" in plan)) return "";
    for (const op of plan.ops) {
      if (op.op === "upsert" && op.path.includes("infra/catalog/")) {
        return op.content;
      }
    }
    return "";
  };

  /** baseCurrent seeds templates only for the given envs (+preview); production needs its own. */
  const currentWithProduction = (envs: readonly string[]): EnvPlanCurrent => {
    const base = baseCurrent(envs);
    return {
      ...base,
      templateOverlayByEnv: {
        ...base.templateOverlayByEnv,
        production: TEMPLATE_OVERLAY,
      },
      templateExternalSecretByEnv: {
        ...base.templateExternalSecretByEnv,
        production: TEMPLATE_EXTERNAL_SECRET,
      },
      appsetsKustomizationByEnv: {
        ...base.appsetsKustomizationByEnv,
        production: kustWith("production", ["operator"]),
      },
    };
  };

  it("promoting candidate-a → production moves the activity authority with it", () => {
    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: true,
      current: currentWithProduction(["candidate-a"]),
    });

    // Without this, the node deploys and serves in production while its webhooks — which
    // GitHub delivers to production ONLY — are dropped `unclaimed`, silently, forever.
    expect(catalogOf(plan)).toContain("activity_env: production");
    expect(catalogOf(plan)).not.toContain("activity_env: candidate-a");
  });

  it("promoting to preview moves authority up from candidate-a", () => {
    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });

    expect(catalogOf(plan)).toContain("activity_env: preview");
  });

  it("carries a trailing comment across the activity_env rewrite", () => {
    // ACTIVITY_ENV_LINE_RE matches the trailing comment, so a naive whole-line replace
    // deletes it. These rows carry load-bearing comments and a silent drop in a generated
    // PR is exactly what nobody notices.
    const base = baseCurrent(["candidate-a"]);
    const current = {
      ...currentWithProduction(["candidate-a"]),
      catalog: base.catalog.replace(
        "activity_env: candidate-a",
        "activity_env: candidate-a # birth authority, moves on promotion"
      ),
    };

    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: true,
      current,
    });

    expect(catalogOf(plan)).toContain(
      "activity_env: production # birth authority, moves on promotion"
    );
  });

  it("takes the HIGHEST deployed env, not just the one being added", () => {
    // The subtle case my first rule got wrong: this node is already in production, and
    // adding `preview` must not pull its authority DOWN to preview — preview cannot ingest
    // either. Authority is max(nextEnvs), which is monotonic by construction.
    const plan = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: currentWithProduction(["candidate-a", "production"]),
    });

    expect(catalogOf(plan)).toContain("activity_env: production");
    expect(catalogOf(plan)).not.toContain("activity_env: preview");
  });
});

// ── ADD_DERIVES_PLACEMENT (story.5039) ──────────────────────────────────────────────────────────

/** An externally built (source_repo) row for the DERIVED-add tests — owner org selects the writer. */
const externallyBuiltCatalog = (
  envs: readonly string[],
  ownerOrg = "cogni-dao"
): string =>
  catalogWith(envs).replace(
    "envs: [",
    `source_repo: https://github.com/${ownerOrg}/${SLUG}.git\nimage_repository: ghcr.io/${ownerOrg}/${SLUG}\nenvs: [`
  );

describe("planEnvAddShape (ADD_DERIVES_PLACEMENT, story.5039)", () => {
  it("derives k3s with no cells + the env's own control env for an in-repo row", () => {
    expect(planEnvAddShape(catalogWith(["preview"]), "candidate-a")).toEqual({
      placement: "k3s",
      computeApi: null,
      controlEnv: "candidate-a",
    });
  });

  it("derives akash + crossplane + the PRODUCTION control env for a cogni-dao row's non-production lane", () => {
    expect(
      planEnvAddShape(externallyBuiltCatalog(["production"]), "candidate-a")
    ).toEqual({
      placement: "akash",
      computeApi: "crossplane",
      controlEnv: "production",
    });
  });

  it("production's control env is production itself", () => {
    expect(
      planEnvAddShape(externallyBuiltCatalog(["candidate-a"]), "production")
        .controlEnv
    ).toBe("production");
  });

  it("throws compute_authority_unavailable (422) when no actuator writer resolves for the owner org", () => {
    // An org outside the CROSSPLANE_ACTUATOR_WRITERS map — the schema makes an akash env without
    // compute_api INVALID, so the verb must refuse loudly rather than author an unmergeable PR.
    const call = () =>
      planEnvAddShape(
        externallyBuiltCatalog(["production"], "unknown-org"),
        "candidate-a"
      );
    expect(call).toThrowError(
      expect.objectContaining({
        code: "compute_authority_unavailable",
        status: 422,
      })
    );
    // The message names the fix location: the reviewed writer map.
    expect(call).toThrow(/CROSSPLANE_ACTUATOR_WRITERS/);
  });
});

describe("buildEnvDeltaPlan — akash-derived ADD (story.5039)", () => {
  /** Current state for adding candidate-a to an akash row: control env = production. */
  const akashAddCurrent = (): EnvPlanCurrent => ({
    catalog: externallyBuiltCatalog(["preview"]),
    templateOverlayByEnv: { "candidate-a": TEMPLATE_OVERLAY },
    templateExternalSecretByEnv: { "candidate-a": TEMPLATE_EXTERNAL_SECRET },
    appsetTemplate: APPSET_TEMPLATE,
    appsetsKustomizationByEnv: {
      production: kustWith("production", ["blue", "operator"]),
    },
    port: 3200,
    nodePort: 31100,
    schedulerEndpointPatchByEnv: {
      "candidate-a": schedulerPatchFixture(`http://${SLUG}-node-app:3000`),
    },
  });

  it("emits the FULL activation artifact set: catalog cells + control-env appset + scheduler route", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: true,
      current: akashAddCurrent(),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("candidate-a", SLUG),
        externalSecretPath("candidate-a", SLUG),
        // CONTROL_ENV_OWNS_THE_APPSET_DIR (bug.5204): the akash lane's AppSet lives under
        // appsets/production/, filename keeps the workload env.
        appsetPath("production", "candidate-a", SLUG),
        appsetsKustomizationPath("production"),
        schedulerEndpointPatchPath("candidate-a"),
      ].sort()
    );

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
      // The three cells #2301 hand-wrote, explicitly — including the schema-default 0.
      expect(catalogOp.content).toContain(
        "deployment_provider:\n  candidate-a: akash\n" +
          "compute_api:\n  candidate-a: crossplane\n" +
          "lease_generation:\n  candidate-a: 0\n"
      );
    }

    // The pair folds into the PRODUCTION kustomization, env-major before its production lines.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    expect(kustOp?.op).toBe("upsert");
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain(
        "resources:\n  - candidate-a-blue-applicationset.yaml\n  - production-blue-applicationset.yaml"
      );
    }

    // PLACEMENT_DECIDES_THE_ADDRESS at activation (bug.5094): the env's route carries the
    // public host from the first flight — an akash lane has no in-cluster Service.
    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("candidate-a")
    );
    expect(schedulerOp?.op).toBe("upsert");
    if (schedulerOp?.op === "upsert") {
      expect(schedulerOp.content).toContain(
        `${SLUG}=https://${SLUG}-test.cognidao.org,${NODE_ID}=https://${SLUG}-test.cognidao.org`
      );
    }
  });

  it("writes an explicit lease_generation from the caller input", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: true,
      current: akashAddCurrent(),
      leaseGeneration: 3,
    });
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain(
        "lease_generation:\n  candidate-a: 3\n"
      );
    }
  });

  it("throws env_render_inputs_missing naming the CONTROL env when its kustomization is absent", () => {
    const base = akashAddCurrent();
    // The workload env's kustomization is present but the CONTROL env's is not — the exact
    // pre-fix fetch shape (bug.5204: six callers keyed the path on the env alone).
    const current: EnvPlanCurrent = {
      ...base,
      appsetsKustomizationByEnv: {
        "candidate-a": kustWith("candidate-a", ["blue", "operator"]),
      },
    };
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: true,
        current,
      });
    expect(call).toThrowError(
      expect.objectContaining({
        code: "env_render_inputs_missing",
        status: 422,
      })
    );
    expect(call).toThrow(/'production'/);
  });
});

// ── Placement lever (story.5016 T5) ─────────────────────────────────────────────────────────────
//
// NO_DELETE_ON_PLACEMENT: a placement flip NEVER touches the overlay, external-secret, AppSet, or
// appsets kustomization — Argo delivers BOTH the k3s Deployment and the akash ComputeWorkload CR
// through the SAME per-node Application (proof: toks4's candidate-a/preview/production AppSets
// all exist today, fully akash-placed); the overlay's CONTENT differs per placement, but that swap
// is the materializer's job on the deploy branch at the next flight/promote, not this plan's. An
// earlier revision of this verb wrongly copied `planRemove`'s delete set here — these tests pin
// the fix: ops are ONLY ever a catalog upsert and/or a scheduler-endpoint upsert.

/** baseCurrent with an external build plane (source_repo) — akash's eligibility precondition. */
const externallyBuilt = (envs: readonly string[]): EnvPlanCurrent => {
  const base = baseCurrent(envs);
  return {
    ...base,
    catalog: base.catalog.replace(
      "envs: [",
      `source_repo: https://github.com/cogni-dao/${SLUG}.git\nimage_repository: ghcr.io/cogni-dao/${SLUG}\nenvs: [`
    ),
  };
};

describe("buildPlacementPlan — akash", () => {
  it("upserts deployment_provider and moves the scheduler-worker route — NOTHING else", () => {
    const res = buildPlacementPlan({
      slug: SLUG,
      env: "preview",
      placement: "akash",
      current: externallyBuilt(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("place_akash");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    // NO_DELETE_ON_PLACEMENT — no deletes, no appset/overlay/kustomization ops at all.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [CATALOG_PATH(SLUG), schedulerEndpointPatchPath("preview")].sort()
    );

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain(
        "deployment_provider:\n  preview: akash"
      );
      // envs: reach is untouched — placement is a lane switch, not an undeploy.
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
      // compute_egress_cidrs (absent here) and every other line pass through unchanged.
      expect(catalogOp.content).toContain("source_repo:");
    }

    // PLACEMENT_DECIDES_THE_ADDRESS (bug.5094) — the scheduler-worker's routed URL moves
    // with the flip, to the SAME public host the ComputeWorkload reconciler serves.
    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("preview")
    );
    expect(schedulerOp?.op).toBe("upsert");
    if (schedulerOp?.op === "upsert") {
      expect(schedulerOp.content).toContain(
        `${SLUG}=https://${SLUG}-preview.cognidao.org,${NODE_ID}=https://${SLUG}-preview.cognidao.org`
      );
    }
  });

  // story.5016: the levelup/preview→akash placement PR (#2162) that motivated this fix — merged
  // with NO scheduler-routing op at all, leaving the preview scheduler-worker dialing
  // `http://levelup-node-app:3000` after the earlier (now-superseded) k3s-lane deletes landed. This
  // pins the fix: the plan MUST carry the updated preview node-endpoints patch with the
  // public-host route, and MUST NOT touch the appset/overlay lane at all.
  it("levelup preview→akash: plan carries the updated preview node-endpoints patch with the public-host route", () => {
    const levelupNodeId = "557d8b59-8e3b-42f0-9aeb-a5c171296556";
    const current: EnvPlanCurrent = {
      catalog: `name: levelup
type: node
port: 3200
node_port: 31800
dockerfile: nodes/levelup/app/Dockerfile
source_repo: https://github.com/cogni-dao/levelup.git
image_repository: ghcr.io/cogni-dao/levelup
envs: [preview, production]
activity_env: production
path_prefix: nodes/levelup/
node_id: ${levelupNodeId}
`,
      templateOverlayByEnv: {},
      appsetsKustomizationByEnv: {
        preview: kustWith("preview", ["levelup", "operator"]),
      },
      schedulerEndpointPatchByEnv: {
        preview: `apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-worker-config
data:
  COGNI_NODE_ENDPOINTS: "levelup=http://levelup-node-app:3000,${levelupNodeId}=http://levelup-node-app:3000"
`,
      },
    };

    const res = buildPlacementPlan({
      slug: "levelup",
      env: "preview",
      placement: "akash",
      current,
    });
    expect(res.kind).toBe("place_akash");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    // The appset/overlay/kustomization lane is UNTOUCHED — only catalog + scheduler routing.
    expect(paths(res.ops).sort()).toEqual(
      [CATALOG_PATH("levelup"), schedulerEndpointPatchPath("preview")].sort()
    );

    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("preview")
    );
    expect(schedulerOp?.op).toBe("upsert");
    if (schedulerOp?.op === "upsert") {
      expect(schedulerOp.content).toContain(
        `levelup=https://levelup-preview.cognidao.org,${levelupNodeId}=https://levelup-preview.cognidao.org`
      );
    }
  });

  it("already-akash with the route already public → no_changes (pure catalog re-application is a no-op too)", () => {
    const base = externallyBuilt(["candidate-a", "preview"]);
    const current: EnvPlanCurrent = {
      ...base,
      catalog: base.catalog.replace(
        "envs: [candidate-a, preview]\n",
        "envs: [candidate-a, preview]\ndeployment_provider:\n  preview: akash\n"
      ),
      schedulerEndpointPatchByEnv: {
        ...base.schedulerEndpointPatchByEnv,
        preview: schedulerPatchFixture(`https://${SLUG}-preview.cognidao.org`),
      },
    };
    expect(
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "akash",
        current,
      }).kind
    ).toBe("no_changes");
  });

  it("refuses akash for a node without source_repo (no external build plane)", () => {
    const call = () =>
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "akash",
        current: baseCurrent(["candidate-a", "preview"]),
      });
    expect(call).toThrowError(
      expect.objectContaining({
        code: "akash_requires_source_repo",
        status: 422,
      })
    );
  });

  it("refuses placement for an env the node is not deployed to", () => {
    const call = () =>
      buildPlacementPlan({
        slug: SLUG,
        env: "production",
        placement: "akash",
        current: externallyBuilt(["candidate-a"]),
      });
    expect(call).toThrowError(
      expect.objectContaining({ code: "env_not_deployed", status: 422 })
    );
  });

  it("refuses to move operator off k3s (it is the control plane serving this verb)", () => {
    const call = () =>
      buildPlacementPlan({
        slug: "operator",
        env: "candidate-a",
        placement: "akash",
        current: externallyBuilt(["candidate-a"]),
      });
    expect(call).toThrowError(
      expect.objectContaining({ code: "operator_node_immutable", status: 422 })
    );
  });

  it("places node-template on akash like an ordinary node — NO_DELETE_ON_PLACEMENT applies to it too", () => {
    // node-template's real catalog row + an external build plane (akash's eligibility precondition).
    const TEMPLATE_NODE_ID = "22222222-2222-4222-8222-222222222222";
    const templateCatalogWith = (envs: readonly string[]): string =>
      `name: node-template
type: node
port: 3200
node_port: 30200
dockerfile: nodes/node-template/app/Dockerfile
source_repo: https://github.com/cogni-dao/node-template.git
image_repository: ghcr.io/cogni-dao/node-template
envs: [${envs.join(", ")}]
activity_env: production
path_prefix: nodes/node-template/
node_id: ${TEMPLATE_NODE_ID}
`;
    const current: EnvPlanCurrent = {
      catalog: templateCatalogWith(["candidate-a"]),
      templateOverlayByEnv: { "candidate-a": TEMPLATE_OVERLAY },
      templateExternalSecretByEnv: { "candidate-a": TEMPLATE_EXTERNAL_SECRET },
      appsetTemplate: APPSET_TEMPLATE,
      appsetsKustomizationByEnv: {
        "candidate-a": kustWith("candidate-a", ["blue", "node-template"]),
      },
      port: 3200,
      nodePort: 30200,
      schedulerEndpointPatchByEnv: {
        "candidate-a": `apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-worker-config
data:
  COGNI_NODE_ENDPOINTS: "node-template=http://node-template-node-app:3000,${TEMPLATE_NODE_ID}=http://node-template-node-app:3000"
`,
      },
    };
    const res = buildPlacementPlan({
      slug: "node-template",
      env: "candidate-a",
      placement: "akash",
      current,
    });
    expect(res.kind).toBe("place_akash");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    // NO_DELETE_ON_PLACEMENT — node-template's overlay/external-secret/appset are ALL untouched:
    // TEMPLATE_OVERLAY_IS_RENDER_SOURCE's special-case no longer applies to placement (nothing to
    // special-case once placement deletes nothing).
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH("node-template"),
        schedulerEndpointPatchPath("candidate-a"),
      ].sort()
    );
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain(
        "deployment_provider:\n  candidate-a: akash"
      );
      expect(catalogOp.content).toContain("envs: [candidate-a]");
    }
    // PLACEMENT_DECIDES_THE_ADDRESS (bug.5094) — the scheduler-worker's routed URL for
    // node-template moves with the flip, to the SAME public host the ComputeWorkload
    // reconciler serves (host_for_node convention: candidate-a → `<slug>-test.<root>`).
    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("candidate-a")
    );
    expect(schedulerOp?.op).toBe("upsert");
    if (schedulerOp?.op === "upsert") {
      expect(schedulerOp.content).toContain(
        `node-template=https://node-template-test.cognidao.org,${TEMPLATE_NODE_ID}=https://node-template-test.cognidao.org`
      );
    }
  });
});

describe("buildPlacementPlan — k3s restore", () => {
  const akashCurrent = (): EnvPlanCurrent => {
    const base = externallyBuilt(["candidate-a", "preview"]);
    return {
      ...base,
      catalog: base.catalog.replace(
        "envs: [candidate-a, preview]\n",
        "envs: [candidate-a, preview]\ndeployment_provider:\n  preview: akash\n"
      ),
      // Currently routed to the public host — the restore must move it back in-cluster.
      schedulerEndpointPatchByEnv: {
        ...base.schedulerEndpointPatchByEnv,
        preview: schedulerPatchFixture(`https://${SLUG}-preview.cognidao.org`),
      },
    };
  };

  it("drops the map entry and moves the scheduler-worker route back in-cluster — NOTHING else", () => {
    const res = buildPlacementPlan({
      slug: SLUG,
      env: "preview",
      placement: "k3s",
      current: akashCurrent(),
    });
    expect(res.kind).toBe("place_k3s");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    // NO_DELETE_ON_PLACEMENT — no appset/overlay/kustomization RESTORE render either: those files
    // were never touched by the akash flip, so there is nothing to restore.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [CATALOG_PATH(SLUG), schedulerEndpointPatchPath("preview")].sort()
    );

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      // The emptied block is dropped entirely (k3s is the schema default).
      expect(catalogOp.content).not.toContain("deployment_provider");
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    // PLACEMENT_DECIDES_THE_ADDRESS (bug.5094) — the restore moves the scheduler-worker's
    // routed URL back to the in-cluster Service DNS convention.
    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("preview")
    );
    expect(schedulerOp?.op).toBe("upsert");
    if (schedulerOp?.op === "upsert") {
      expect(schedulerOp.content).toContain(
        `${SLUG}=http://${SLUG}-node-app:3000,${NODE_ID}=http://${SLUG}-node-app:3000`
      );
    }
  });

  it("is idempotent: already on the k3s default → no_changes (no restore render)", () => {
    expect(
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "k3s",
        current: externallyBuilt(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
  });

  it("k3s is allowed WITHOUT source_repo (only akash needs the external build plane)", () => {
    expect(
      buildPlacementPlan({
        slug: SLUG,
        env: "preview",
        placement: "k3s",
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
  });
});

// ── REMOVE_COMPLETES_THE_ROW (story.5039 PR-B) ──────────────────────────────────────────────────
//
// `present:false` on an akash lane must (1) drop the removed env's placement cells with the env —
// a stranded cell violates NO_PLACEMENT_FOR_UNDECLARED_ENV (tests/ci-invariants/
// env-declaration-completeness.spec.ts) — (2) delete the AppSet at its CONTROL-env path (the dir
// the add wrote it into, derived from the PRE-mutation catalog), and (3) restore the env's
// scheduler-worker route to the k3s in-cluster default (the byte-inverse of the add's write).

describe("buildEnvDeltaPlan — akash REMOVE (REMOVE_COMPLETES_THE_ROW, story.5039 PR-B)", () => {
  /** An akash-activated candidate-a lane the way planAdd authors it (control env = production). */
  const akashRemoveCatalog = (): string =>
    externallyBuiltCatalog(["candidate-a", "preview"])
      .replace("activity_env: candidate-a", "activity_env: preview")
      .replace(
        "envs: [candidate-a, preview]\n",
        "envs: [candidate-a, preview]\n" +
          "deployment_provider:\n  candidate-a: akash\n" +
          "compute_api:\n  candidate-a: crossplane\n" +
          "lease_generation:\n  candidate-a: 2\n"
      );

  const PROD_KUST = `${KUST_HEADER}\n  - candidate-a-blue-applicationset.yaml\n  - production-operator-applicationset.yaml\n`;

  const akashRemoveCurrent = (): EnvPlanCurrent => ({
    catalog: akashRemoveCatalog(),
    templateOverlayByEnv: {},
    appsetsKustomizationByEnv: { production: PROD_KUST },
    schedulerEndpointPatchByEnv: {
      "candidate-a": schedulerPatchFixture(`https://${SLUG}-test.cognidao.org`),
    },
  });

  /**
   * NO_PLACEMENT_FOR_UNDECLARED_ENV, asserted in the invariant's own shape: parse the emitted
   * catalog and require every placement cell's env to be in `envs:` — the exact check
   * tests/ci-invariants/env-declaration-completeness.spec.ts runs over infra/catalog.
   */
  const assertNoStrandedCells = (catalogYaml: string): void => {
    const row = parseYaml(catalogYaml) as {
      envs?: string[];
      deployment_provider?: Record<string, string>;
      compute_api?: Record<string, string>;
      lease_generation?: Record<string, number>;
    };
    const envs = row.envs ?? [];
    for (const block of [
      "deployment_provider",
      "compute_api",
      "lease_generation",
    ] as const) {
      for (const env of Object.keys(row[block] ?? {})) {
        expect(envs, `${block}.${env} names an env not in envs:`).toContain(
          env
        );
      }
    }
  };

  it("drops the env's three placement cells, deletes the CONTROL-env appset, and restores the scheduler route", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      current: akashRemoveCurrent(),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["preview"]);
    // CONTROL_ENV_OWNS_THE_APPSET_DIR on the remove side: the akash lane's AppSet leaves from
    // appsets/production/, NOT appsets/candidate-a/ (where PR-A's env-keyed remove pointed).
    expect(deletes(res.ops).sort()).toEqual(
      [
        overlayPath("candidate-a", SLUG),
        externalSecretPath("candidate-a", SLUG),
        appsetPath("production", "candidate-a", SLUG),
      ].sort()
    );

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [preview]");
      // The single-cell blocks drop entirely (schema minProperties: 1).
      expect(catalogOp.content).not.toContain("deployment_provider");
      expect(catalogOp.content).not.toContain("compute_api");
      expect(catalogOp.content).not.toContain("lease_generation");
      assertNoStrandedCells(catalogOp.content);
    }

    // The (candidate-a, blue) pair leaves the PRODUCTION kustomization; foreign pairs survive.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    expect(kustOp?.op).toBe("upsert");
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "candidate-a-blue-applicationset.yaml"
      );
      expect(kustOp.content).toContain(
        "production-operator-applicationset.yaml"
      );
    }

    // Byte-inverse of planAdd's scheduler write: back to the k3s in-cluster default.
    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("candidate-a")
    );
    expect(schedulerOp?.op).toBe("upsert");
    if (schedulerOp?.op === "upsert") {
      expect(schedulerOp.content).toContain(
        `${SLUG}=http://${SLUG}-node-app:3000,${NODE_ID}=http://${SLUG}-node-app:3000`
      );
    }
  });

  it("drops ONLY the removed env's cells when other envs are placed too", () => {
    const base = akashRemoveCurrent();
    const current: EnvPlanCurrent = {
      ...base,
      catalog: base.catalog
        .replace(
          "deployment_provider:\n  candidate-a: akash\n",
          "deployment_provider:\n  candidate-a: akash\n  preview: akash\n"
        )
        .replace(
          "compute_api:\n  candidate-a: crossplane\n",
          "compute_api:\n  candidate-a: crossplane\n  preview: crossplane\n"
        )
        .replace(
          "lease_generation:\n  candidate-a: 2\n",
          "lease_generation:\n  candidate-a: 2\n  preview: 1\n"
        ),
    };
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      current,
    });
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain(
        "deployment_provider:\n  preview: akash\n"
      );
      expect(catalogOp.content).toContain(
        "compute_api:\n  preview: crossplane\n"
      );
      expect(catalogOp.content).toContain("lease_generation:\n  preview: 1\n");
      expect(catalogOp.content).not.toContain("candidate-a: akash");
      assertNoStrandedCells(catalogOp.content);
    }
  });

  it("emits no scheduler op when the route is already the in-cluster default (idempotent restore)", () => {
    const base = akashRemoveCurrent();
    const current: EnvPlanCurrent = {
      ...base,
      schedulerEndpointPatchByEnv: {
        "candidate-a": schedulerPatchFixture(`http://${SLUG}-node-app:3000`),
      },
    };
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "candidate-a",
      present: false,
      current,
    });
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    expect(paths(res.ops)).not.toContain(
      schedulerEndpointPatchPath("candidate-a")
    );
  });

  it("throws env_render_inputs_missing naming the CONTROL env when its kustomization is absent", () => {
    const base = akashRemoveCurrent();
    // The workload env's kustomization is present but the CONTROL env's is not — the exact
    // pre-fix fetch shape (PR-A's remove branch keyed the fetch on the env alone).
    const current: EnvPlanCurrent = {
      ...base,
      appsetsKustomizationByEnv: {
        "candidate-a": kustWith("candidate-a", ["blue", "operator"]),
      },
    };
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current,
      });
    expect(call).toThrowError(
      expect.objectContaining({
        code: "env_render_inputs_missing",
        status: 422,
      })
    );
    expect(call).toThrow(/'production'/);
  });

  it("keeps node-template's overlay files on an akash remove (TEMPLATE_OVERLAY_IS_RENDER_SOURCE holds)", () => {
    const TEMPLATE_NODE_ID = "22222222-2222-4222-8222-222222222222";
    const current: EnvPlanCurrent = {
      catalog: `name: node-template
type: node
port: 3200
node_port: 30200
source_repo: https://github.com/cogni-dao/node-template.git
image_repository: ghcr.io/cogni-dao/node-template
envs: [candidate-a, production]
deployment_provider:
  candidate-a: akash
compute_api:
  candidate-a: crossplane
lease_generation:
  candidate-a: 0
activity_env: production
path_prefix: nodes/node-template/
node_id: ${TEMPLATE_NODE_ID}
`,
      templateOverlayByEnv: {},
      appsetsKustomizationByEnv: {
        production: `${KUST_HEADER}\n  - candidate-a-node-template-applicationset.yaml\n  - production-node-template-applicationset.yaml\n`,
      },
      schedulerEndpointPatchByEnv: {
        "candidate-a": `apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-worker-config
data:
  COGNI_NODE_ENDPOINTS: "node-template=https://node-template-test.cognidao.org,${TEMPLATE_NODE_ID}=https://node-template-test.cognidao.org"
`,
      },
    };
    const res = buildEnvDeltaPlan({
      slug: "node-template",
      env: "candidate-a",
      present: false,
      current,
    });
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");
    // REDUCED delete set at the CONTROL-env path; overlay files stay (render source).
    expect(deletes(res.ops)).toEqual([
      appsetPath("production", "candidate-a", "node-template"),
    ]);
    expect(paths(res.ops)).not.toContain(
      overlayPath("candidate-a", "node-template")
    );
    // Cells still drop and the scheduler route still restores — the row completes.
    const catalogOp = res.ops.find(
      (o) => o.path === CATALOG_PATH("node-template")
    );
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).not.toContain("deployment_provider");
      assertNoStrandedCells(catalogOp.content);
    }
    const schedulerOp = res.ops.find(
      (o) => o.path === schedulerEndpointPatchPath("candidate-a")
    );
    expect(schedulerOp?.op).toBe("upsert");
  });
});
