// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2026 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/env-membership-plan`
 * Purpose: Pin the pure env-delta planner — add-env inserts, remove-env sha:null deletions +
 *   regenerated kustomization, and the ATOMIC_PER_ENV + idempotency invariants. Every env is an
 *   independent toggle while the non-empty deploy set and singleton activity authority remain valid.
 * Scope: Pure unit tests over hand-built control-plane fixtures (no Octokit).
 * Invariants: ATOMIC_PER_ENV, IDEMPOTENT, DELETE_VIA_SHA_NULL.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/env-membership-plan
 * @public
 */

import { describe, expect, it } from "vitest";

import {
  appsetPath,
  appsetsKustomizationPath,
  buildEnvDeltaPlan,
  CATALOG_PATH,
  type EnvPlanCurrent,
  EnvPlanError,
  type EnvPlanOp,
  externalSecretPath,
  overlayPath,
} from "./env-membership-plan";

const SLUG = "blue";

const KUST_HEADER = `# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# GENERATED by scripts/ci/render-node-appset.sh — DO NOT EDIT BY HAND.
# This env's per-node ApplicationSets, reconciled with prune by the per-env
# cogni-<env>-appsets app-of-apps (../../<env>-appsets-application.yaml). One AppSet
# per (env, node) for structural LANE_ISOLATION (axiom 18). Regenerate: pnpm gen:node-appset
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:`;

const kustWith = (env: string, nodes: readonly string[]): string =>
  `${KUST_HEADER}\n${nodes
    .map((n) => `  - ${env}-${n}-applicationset.yaml`)
    .join("\n")}\n`;

// node-template overlay carrying the node-at-root migrate command renderOverlay requires.
const TEMPLATE_OVERLAY = `namespace: cogni-candidate-a-node-template
resources:
  - ../../../base/node-app
patches:
  - target: { kind: Service }
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30200
images:
  - name: node-app
    newName: ghcr.io/cogni-dao/cogni-template-node-template
initContainers:
  migrate: exec node /app/app/migrate.mjs /app/app/migrations
`;

// node-template overlay's external-secret.yaml (the ESO producer). renderOverlayFile only
// slug/port-renames it — node-template → blue everywhere, no migrate guard.
const TEMPLATE_EXTERNAL_SECRET = `apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  labels:
    app.kubernetes.io/component: node-template
spec:
  target:
    name: node-template-env-secrets
  dataFrom:
    - extract:
        key: candidate-a/node-template
`;

const APPSET_TEMPLATE = `metadata:
  name: cogni-__ENV__-__NODE__
spec:
  generators:
    - git:
        repoURL: __DEPLOYMENT_PARENT_REPO_URL__
        files:
          - path: "infra/catalog/__NODE__.yaml"
`;

const catalogWith = (envs: readonly string[]): string =>
  `name: ${SLUG}
type: node
port: 3200
node_port: 31100
dockerfile: nodes/${SLUG}/app/Dockerfile
image_tag_suffix: "-${SLUG}"
migrator_tag_suffix: "-${SLUG}-migrate"
candidate_a_branch: deploy/candidate-a-${SLUG}
preview_branch: deploy/preview-${SLUG}
production_branch: deploy/production-${SLUG}
envs: [${envs.join(", ")}]
activity_env: ${envs[0] ?? "candidate-a"}
path_prefix: nodes/${SLUG}/
`;

function baseCurrent(envs: readonly string[]): EnvPlanCurrent {
  const appsetsKustomizationByEnv: Record<string, string> = {};
  const templateOverlayByEnv: Record<string, string> = {};
  const templateExternalSecretByEnv: Record<string, string> = {};
  for (const e of envs) {
    appsetsKustomizationByEnv[e] = kustWith(e, ["blue", "operator"]);
    templateOverlayByEnv[e] = TEMPLATE_OVERLAY;
    templateExternalSecretByEnv[e] = TEMPLATE_EXTERNAL_SECRET;
  }
  // preview is an env we ADD in tests, so make its template overlay + kustomization available.
  appsetsKustomizationByEnv.preview ??= kustWith("preview", ["operator"]);
  templateOverlayByEnv.preview ??= TEMPLATE_OVERLAY;
  templateExternalSecretByEnv.preview ??= TEMPLATE_EXTERNAL_SECRET;
  return {
    catalog: catalogWith(envs),
    templateOverlayByEnv,
    templateExternalSecretByEnv,
    appsetTemplate: APPSET_TEMPLATE,
    deploymentParentRepoUrl: "https://github.com/cogni-dao/cogni.git",
    appsetsKustomizationByEnv,
    port: 3200,
    nodePort: 31100,
  };
}

const paths = (ops: readonly EnvPlanOp[]): string[] => ops.map((o) => o.path);
const deletes = (ops: readonly EnvPlanOp[]): string[] =>
  ops.filter((o) => o.op === "delete").map((o) => o.path);

describe("buildEnvDeltaPlan — ADD env", () => {
  it("inserts catalog edit + overlay + appset + kustomization fold for the added env", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a"]),
    });
    expect(res.kind).toBe("add");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // No deletes on an add.
    expect(deletes(res.ops)).toEqual([]);
    expect(paths(res.ops).sort()).toEqual(
      [
        CATALOG_PATH(SLUG),
        overlayPath("preview", SLUG),
        externalSecretPath("preview", SLUG),
        appsetPath("preview", SLUG),
        appsetsKustomizationPath("preview"),
      ].sort()
    );
    // ESO producer is cloned with the slug rename applied.
    const esOp = res.ops.find(
      (o) => o.path === externalSecretPath("preview", SLUG)
    );
    expect(esOp?.op).toBe("upsert");
    if (esOp?.op === "upsert") {
      expect(esOp.content).toContain("name: blue-env-secrets");
      expect(esOp.content).not.toContain("node-template");
    }

    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    expect(catalogOp?.op).toBe("upsert");
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    // Overlay rename applied (node-template → blue).
    const overlayOp = res.ops.find(
      (o) => o.path === overlayPath("preview", SLUG)
    );
    if (overlayOp?.op === "upsert") {
      expect(overlayOp.content).toContain("cogni-candidate-a-blue");
    }
    // appsets kustomization now lists blue under preview.
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("preview")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).toContain("preview-blue-applicationset.yaml");
    }
    const appsetOp = res.ops.find(
      (o) => o.path === appsetPath("preview", SLUG)
    );
    if (appsetOp?.op === "upsert") {
      expect(appsetOp.content).toContain(
        "repoURL: https://github.com/cogni-dao/cogni.git"
      );
    }
  });

  it("is idempotent when the env is already present", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "preview",
      present: true,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — REMOVE env (partial)", () => {
  it("drops the env line + sha:null deletes overlay+appset + regenerates kustomization", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview", "production"]),
    });
    expect(res.kind).toBe("remove");
    if (res.kind === "no_changes") throw new Error("unexpected no_changes");

    expect(res.nextEnvs).toEqual(["candidate-a", "preview"]);
    // Overlay + appset are DELETED (sha:null in the adapter).
    expect(deletes(res.ops).sort()).toEqual(
      [
        overlayPath("production", SLUG),
        externalSecretPath("production", SLUG),
        appsetPath("production", SLUG),
      ].sort()
    );
    // Catalog edited + kustomization regenerated without blue.
    const catalogOp = res.ops.find((o) => o.path === CATALOG_PATH(SLUG));
    if (catalogOp?.op === "upsert") {
      expect(catalogOp.content).toContain("envs: [candidate-a, preview]");
    }
    const kustOp = res.ops.find(
      (o) => o.path === appsetsKustomizationPath("production")
    );
    if (kustOp?.op === "upsert") {
      expect(kustOp.content).not.toContain(
        "production-blue-applicationset.yaml"
      );
    }
    // The catalog row itself is NEVER deleted on a remove (per-node state stays).
    expect(deletes(res.ops)).not.toContain(CATALOG_PATH(SLUG));
  });

  it("is idempotent when the env is already absent", () => {
    const res = buildEnvDeltaPlan({
      slug: SLUG,
      env: "production",
      present: false,
      current: baseCurrent(["candidate-a", "preview"]),
    });
    expect(res.kind).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — safe removals", () => {
  it("rejects removing the current activity authority even when other deployments survive", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });

    expect(call).toThrowError(
      expect.objectContaining({
        code: "activity_authority_cutover_required",
        status: 422,
      })
    );
  });

  it("rejects removing the LAST remaining environment", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a"]),
      });

    expect(call).toThrowError(
      expect.objectContaining({
        code: "final_environment_required",
        status: 422,
      })
    );
  });

  it("is idempotent both directions on candidate-a (add already-present / remove already-absent)", () => {
    // add candidate-a when already present → no_changes
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: true,
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
    // remove candidate-a when already absent → no_changes (no authority mutation is attempted)
    expect(
      buildEnvDeltaPlan({
        slug: SLUG,
        env: "candidate-a",
        present: false,
        current: baseCurrent(["preview"]),
      }).kind
    ).toBe("no_changes");
  });
});

describe("buildEnvDeltaPlan — TEMPLATE_NODE_IMMUTABLE", () => {
  it("refuses to remove node-template from an env (it is the per-env overlay template)", () => {
    const call = () =>
      buildEnvDeltaPlan({
        slug: "node-template",
        env: "candidate-a",
        present: false,
        current: baseCurrent(["candidate-a", "preview", "production"]),
      });
    expect(call).toThrow(EnvPlanError);
    try {
      call();
      throw new Error("expected EnvPlanError");
    } catch (e) {
      expect(e).toBeInstanceOf(EnvPlanError);
      expect((e as EnvPlanError).code).toBe("template_node_immutable");
      expect((e as EnvPlanError).status).toBe(422);
    }
  });

  it("does NOT block adding node-template (idempotent — it already lives in every env)", () => {
    expect(
      buildEnvDeltaPlan({
        slug: "node-template",
        env: "candidate-a",
        present: true,
        current: baseCurrent(["candidate-a", "preview"]),
      }).kind
    ).toBe("no_changes");
  });
});
