apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spawny-boi-compute-env-secrets-reader
  namespace: cogni-preview
subjects:
  - kind: ServiceAccount
    name: operator-compute-workload-controller
    namespace: cogni-preview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spawny-boi-compute-env-secrets-reader
