apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cogni-preview
resources:
  - xcomputeworkload.yaml
  - compute-env-external-secret.yaml
  - compute-env-secret-role.yaml
  - compute-env-secret-role-binding.yaml
