// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/node-app-scaffold/gens/caddyfile`
 * Purpose: Pin `insertCaddyBlock` to the byte-exact output of `scripts/ci/render-caddyfile.sh`.
 * Scope: Pure-function unit test — small before→after fixtures for first / middle / append-last
 *   insertion positions, plus the duplicate guard. No IO, no scaffolding.
 * Invariants: emitted block mirrors `emit_site_block`; non-primary nodes stay in `sort` order.
 * Side-effects: none
 * Links: src/shared/node-app-scaffold/gens/caddyfile.ts, scripts/ci/render-caddyfile.sh
 * @public
 */

import { describe, expect, it } from "vitest";
import { insertCaddyBlock } from "@/shared/node-app-scaffold/gens/caddyfile";

const HEADER = `# GENERATED by scripts/ci/render-caddyfile.sh from infra/catalog/*.yaml —
# DO NOT EDIT BY HAND.
{
  log {
    level INFO
  }
}

# Redirect www to non-www (canonical operator domain)
www.{$DOMAIN} {
  redir https://{$DOMAIN}{uri} permanent
}

# ── operator (primary domain) → k3s NodePort 30000 ──────────────────────
{$DOMAIN} {
  reverse_proxy {$OPERATOR_UPSTREAM:app:3000}
}
`;

/** Exactly the bytes `emit_site_block` produces for a non-primary node. */
function block(slug: string, upper: string, port: number): string {
  return `# ── ${slug} node → k3s NodePort ${port} ──────────────────────────────────
{$${upper}_DOMAIN:${slug}.localhost} {
  encode zstd gzip

  @public path /api/v1/public/*
  handle @public {
    reverse_proxy {$${upper}_UPSTREAM:host.docker.internal:${port}} {
      header_up X-Real-IP {remote_host}
      transport http {
        response_header_timeout 10s
      }
    }
  }

  reverse_proxy {$${upper}_UPSTREAM:host.docker.internal:${port}}

  log {
    format json
    output stdout
  }
}
`;
}

const RESY = block("resy", "RESY", 30300);
const WITH_RESY = `${HEADER}\n${RESY}`;

describe("insertCaddyBlock", () => {
  it("appends a node that sorts last (resy → ztest)", () => {
    const ZTEST = block("ztest", "ZTEST", 31999);
    expect(insertCaddyBlock(WITH_RESY, "ztest", 31999)).toBe(
      `${WITH_RESY}\n${ZTEST}`
    );
  });

  it("inserts a node that sorts first among non-primary (aaa before resy)", () => {
    const AAA = block("aaa", "AAA", 31001);
    expect(insertCaddyBlock(WITH_RESY, "aaa", 31001)).toBe(
      `${HEADER}\n${AAA}\n${RESY}`
    );
  });

  it("splices a node in the middle, preserving sort order", () => {
    const ZEBRA = block("zebra", "ZEBRA", 31002);
    const ZTEST = block("ztest", "ZTEST", 31999);
    const seeded = `${WITH_RESY}\n${ZTEST}`; // resy, ztest
    // zebra sorts between resy and ztest.
    expect(insertCaddyBlock(seeded, "zebra", 31002)).toBe(
      `${WITH_RESY}\n${ZEBRA}\n${ZTEST}`
    );
  });

  it("translates dashes to underscores in the env-var slug", () => {
    const out = insertCaddyBlock(WITH_RESY, "node-x", 31003);
    expect(out).toContain("{$NODE_X_DOMAIN:node-x.localhost} {");
    expect(out).toContain(
      "reverse_proxy {$NODE_X_UPSTREAM:host.docker.internal:31003}"
    );
  });

  it("rejects a node already present", () => {
    expect(() => insertCaddyBlock(WITH_RESY, "resy", 30300)).toThrow(
      /already contains a block for node 'resy'/
    );
  });
});
