#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2026 Cogni-DAO
#
# Module: scripts/ci/render-compute-egress-allowlist.sh
# Purpose: Render the per-env decentralized-compute egress allowlist from
#          infra/catalog/*.yaml `compute_egress_cidrs` (CATALOG_IS_SSOT,
#          ci-cd.md axiom 16). Output is the file format consumed by
#          infra/provision/cherry/harden-docker-public-ports.sh:
#          full-line `#` comments + one `CIDR:port,port` allow line per entry.
#
# Scoping — PLACEMENT, not membership (bug.5191): an egress CIDR is a property of
# WHERE a row's workload runs, so a row contributes to <env> only when it BOTH
# deploys there (`envs:`) AND is placed off-cluster there
# (`deployment_provider.<env>: akash`). Unioning on `envs:` alone opened a node's
# Akash provider NAT to the substrate ports of an env whose placement is k3s —
# network reach granted to a provider hosting nothing for that env. K3S_IS_DEFAULT:
# an absent per-env override is k3s, which runs inside the env VM's own cluster and
# needs no provider-NAT hole. Rows without a declaration (or envs without any
# akash-placed declaring row) render an allow-free file, which the harden script
# treats as fail-closed (public DROP stays, no ACCEPTs).
#
# Pure render: reads the catalog, writes stdout. No state mutation. Idempotent
# and deterministic (glob order + first-wins CIDR dedupe).
#
# Usage: render-compute-egress-allowlist.sh <env>            # e.g. candidate-a
# Env:   COGNI_CATALOG_ROOT — override catalog dir (tests; same knob as
#        scripts/ci/lib/image-tags.sh).
# Links: task.5052, story.5016, bug.5191

set -euo pipefail

ENV_NAME="${1:?usage: render-compute-egress-allowlist.sh <env>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CATALOG_ROOT="${COGNI_CATALOG_ROOT:-$REPO_ROOT/infra/catalog}"

# Substrate ports external-compute workloads dial (task.5052). Deliberately
# NARROWER than the harden script's INTERNAL_PORTS: no 8080 (OpenFGA) — authz
# stays unreachable from provider NATs until a workload proves the need.
SUBSTRATE_PORTS="5432,5435,6379,4000,7233"

command -v yq >/dev/null 2>&1 || { echo "[render-compute-egress] ERROR: yq is required" >&2; exit 1; }
[ -d "$CATALOG_ROOT" ] || { echo "[render-compute-egress] ERROR: catalog root not found: $CATALOG_ROOT" >&2; exit 1; }

# ONE placement reader for the whole shell lane — deployment_provider_for_target()
# is the same resolver render-scheduler-worker-endpoints.sh and reconcile-node-dns.sh
# use, so the firewall can never disagree with where the workload was actually sent.
# shellcheck source=scripts/ci/lib/image-tags.sh
source "$SCRIPT_DIR/lib/image-tags.sh"

echo "# GENERATED by scripts/ci/render-compute-egress-allowlist.sh from infra/catalog/*.yaml — do not hand-edit."
echo "# env: ${ENV_NAME} — CIDRs allowed to reach substrate ports ${SUBSTRATE_PORTS}. Empty list = fail-closed."

seen_cidrs=" "
for catalog_file in "$CATALOG_ROOT"/*.yaml; do
  [ -e "$catalog_file" ] || continue
  row_name="$(yq -N '.name // ""' "$catalog_file")"

  # Only rows deployed to this env contribute (deploy ⊆ provisioned).
  yq -N -e ".envs // [] | contains([\"$ENV_NAME\"])" "$catalog_file" >/dev/null 2>&1 || continue

  # …and only where THIS env's placement is off-cluster (bug.5191). A row present
  # in the env under k3s runs inside the VM's own cluster: its provider NAT must
  # not be punched through the public DROP for an env it does not occupy.
  provider="$(deployment_provider_for_target "$row_name" "$ENV_NAME")" || {
    echo "[render-compute-egress] ERROR: unresolvable deployment_provider for '$row_name' in env '$ENV_NAME' ($catalog_file)" >&2
    exit 1
  }
  [ "$provider" = "akash" ] || continue

  count="$(yq -N '.compute_egress_cidrs | length' "$catalog_file")"
  [ "$count" -gt 0 ] 2>/dev/null || continue

  i=0
  while [ "$i" -lt "$count" ]; do
    cidr="$(yq -N ".compute_egress_cidrs[$i].cidr // \"\"" "$catalog_file")"
    comment="$(yq -N ".compute_egress_cidrs[$i].comment // \"\"" "$catalog_file" | head -n1)"
    i=$((i + 1))

    # Fail LOUD at render time (schema also gates this in CI): a malformed CIDR
    # must abort the render, never reach the VM to be warn-skipped there.
    if ! printf '%s' "$cidr" | grep -Eq '^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$'; then
      echo "[render-compute-egress] ERROR: invalid cidr '$cidr' in $catalog_file" >&2
      exit 1
    fi
    if [ -z "$comment" ]; then
      echo "[render-compute-egress] ERROR: missing comment for $cidr in $catalog_file" >&2
      exit 1
    fi

    case "$seen_cidrs" in
      *" $cidr "*)
        echo "# ${row_name}: ${comment} (duplicate of an earlier row; rule already rendered)"
        continue
        ;;
    esac
    seen_cidrs="${seen_cidrs}${cidr} "

    echo "# ${row_name}: ${comment}"
    echo "${cidr}:${SUBSTRATE_PORTS}"
  done
done
