#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# render-scheduler-worker-endpoints.sh — emit scheduler-worker node routing
# from infra/catalog/*.yaml. The worker must poll one Temporal queue per
# repo-spec UUID; adding a type:node catalog entry must therefore add both the
# slug and UUID aliases with no hand-edited endpoint string.
#
# bug.5094 — PLACEMENT DECIDES THE ADDRESS. A node whose catalog row declares
# `deployment_provider.<env>: akash` has no `<slug>-node-app` Service in the
# Cherry cluster, so the in-cluster convention resolves to NXDOMAIN for every
# Cherry-resident caller (observed: `getaddrinfo ENOTFOUND toks4-node-app` in
# scheduler-worker). Routing is therefore rendered TWICE, from ONE catalog:
#
#   base   infra/k8s/base/scheduler-worker/configmap.yaml
#          the placement-DEFAULT (all-k3s) map — a kustomize base default in the
#          same sense as TEMPORAL_NAMESPACE / IMAGE_DIGEST there, which every
#          overlay replaces. Env-invariant, so it can stay in the shared base.
#
#   overlay infra/k8s/overlays/<env>/scheduler-worker/node-endpoints.patch.yaml
#          the env's PROVIDER-RESOLVED map — the value that actually reaches a
#          cluster. Env-variant (an akash node's public host is per-env), so it
#          lives exactly where every other env-variant scheduler-worker setting
#          already lives: the per-env overlay.
#
# No second list of nodes and no second list of envs: nodes come from NODE_TARGETS
# (catalog), envs from `deployment_provider`'s own key set in infra/catalog/_schema.json,
# placement from `deployment_provider.<env>` on the row, and the public host from the
# same host_for_node() the ComputeWorkload publisher, edge Caddyfile and DNS use.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# shellcheck source=scripts/ci/lib/image-tags.sh
source "$SCRIPT_DIR/lib/image-tags.sh"
# shellcheck source=scripts/setup/lib/fork-identity.sh
source "$SCRIPT_DIR/../setup/lib/fork-identity.sh"

CONFIGMAP_PATH="$REPO_ROOT/infra/k8s/base/scheduler-worker/configmap.yaml"
DEPLOYMENT_PATH="$REPO_ROOT/infra/k8s/base/scheduler-worker/deployment.yaml"
OVERLAY_ROOT="$REPO_ROOT/infra/k8s/overlays"
PATCH_BASENAME="node-endpoints.patch.yaml"

# The zone this repo's public hosts hang off. Same default the flight workflows
# use (`vars.FORK_DOMAIN_ROOT || 'cognidao.org'`), so the committed artifact and
# the CI drift gate agree; a fork exports FORK_DOMAIN_ROOT and re-runs --write.
FORK_ROOT="${FORK_DOMAIN_ROOT:-cognidao.org}"

# The deploy envs, derived — never a hand-kept env list. Placement is a property of
# a row, not a gate on the env set (PLACEMENT_DOES_NOT_GATE_PROVISIONING, see
# scripts/ci/tests/reconcile-node-substrate.test.sh). The set is
# `deployment_provider`'s own declared keys in infra/catalog/_schema.json (the ONE
# place placement envs are declared; twin of NODE_DEPLOY_ENVS in the operator's
# gens/envs.ts) intersected with the overlay dirs that actually carry a
# scheduler-worker. Non-deploy slots (candidate-b, canary) are absent from the
# schema, so they keep the all-k3s base default and need no generated patch.
CATALOG_SCHEMA="$REPO_ROOT/infra/catalog/_schema.json"
overlay_envs() {
  local env
  while read -r env; do
    [ -n "$env" ] || continue
    [ -f "$OVERLAY_ROOT/$env/scheduler-worker/kustomization.yaml" ] || continue
    printf '%s\n' "$env"
  done < <(yq -N -p json -o yaml '.properties.deployment_provider.properties | keys | .[]' "$CATALOG_SCHEMA")
}

# Placement-default (all-k3s) map for the shared base ConfigMap.
render() {
  node_internal_service_endpoint_csv
}

# Provider-resolved map for one env.
render_env() {
  local env="$1" domain
  domain="$(domain_for_env "$env" "$FORK_ROOT")" \
    || { echo "[ERROR] cannot derive a public domain for env '$env'" >&2; return 1; }
  node_internal_service_endpoint_csv "$env" "$domain"
}

patch_path() {
  printf '%s/%s/scheduler-worker/%s' "$OVERLAY_ROOT" "$1" "$PATCH_BASENAME"
}

write_patch() {
  local env="$1" file endpoints
  file="$(patch_path "$env")"
  endpoints="$(render_env "$env")" || return 1
  cat >"$file" <<YAML
# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2026 Cogni-DAO
#
# GENERATED by scripts/ci/render-scheduler-worker-endpoints.sh — DO NOT EDIT BY HAND.
# Run: pnpm gen:scheduler-worker-endpoints
#
# bug.5094 — the ${env} PROVIDER-RESOLVED node routing map. Each catalog
# type:node row contributes a slug alias and a repo-spec UUID alias pointing at
# the address a Cherry-resident caller must dial for THIS env: the in-cluster
# Service for deployment_provider=k3s, the node's public canonical URL (the same
# host its ComputeWorkload publishes) for deployment_provider=akash.
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-worker-config
data:
  COGNI_NODE_ENDPOINTS: "${endpoints}"
YAML
}

read_patch() {
  local file
  file="$(patch_path "$1")"
  [ -f "$file" ] || { printf ''; return 0; }
  yq -N '.data.COGNI_NODE_ENDPOINTS // ""' "$file"
}

# Node routing renders from catalog metadata only. A remote-source node's catalog
# `node_id` is written at formation from the fetched repo-spec, and `node_id` is
# immutable — so catalog == repo-spec by construction. The secret-free gate never
# reads node source to "re-verify" it (spec.node-submodule-retirement,
# SECRET_FREE_CI_IS_METADATA_ONLY).
check() {
  local expected actual env kustomization first_envfrom second_envfrom rc=0
  expected="$(render)"
  actual="$(yq -N '.data.COGNI_NODE_ENDPOINTS // ""' "$CONFIGMAP_PATH")"
  if [ "$actual" != "$expected" ]; then
    echo "[ERROR] $CONFIGMAP_PATH has a stale placement-default COGNI_NODE_ENDPOINTS." >&2
    echo "Expected:" >&2
    echo "  $expected" >&2
    echo "Actual:" >&2
    echo "  $actual" >&2
    rc=1
  fi

  # Every env overlay MUST carry the provider-resolved map. This is the exact
  # inverse of the pre-bug.5094 guard ("overlays must not override"): the map is
  # env-variant the moment any node is placed off-cluster, so the base value is a
  # default and the overlay value is the one that reaches a cluster.
  while read -r env; do
    [ -n "$env" ] || continue
    expected="$(render_env "$env")" || { rc=1; continue; }
    actual="$(read_patch "$env")"
    if [ "$actual" != "$expected" ]; then
      echo "[ERROR] $(patch_path "$env") has a stale/absent COGNI_NODE_ENDPOINTS for env '$env'." >&2
      echo "Expected:" >&2
      echo "  $expected" >&2
      echo "Actual:" >&2
      echo "  ${actual:-<missing>}" >&2
      rc=1
    fi
    kustomization="$OVERLAY_ROOT/$env/scheduler-worker/kustomization.yaml"
    if ! grep -q "$PATCH_BASENAME" "$kustomization"; then
      echo "[ERROR] $kustomization does not apply $PATCH_BASENAME — the env would silently fall back to the all-k3s base default." >&2
      rc=1
    fi
  done < <(overlay_envs)

  first_envfrom="$(yq -N '.spec.template.spec.containers[] | select(.name == "scheduler-worker") | .envFrom[0] | keys | .[0]' "$DEPLOYMENT_PATH")"
  second_envfrom="$(yq -N '.spec.template.spec.containers[] | select(.name == "scheduler-worker") | .envFrom[1] | keys | .[0]' "$DEPLOYMENT_PATH")"
  if [ "$first_envfrom" != "secretRef" ] || [ "$second_envfrom" != "configMapRef" ]; then
    echo "[ERROR] scheduler-worker envFrom order must be secretRef then configMapRef." >&2
    echo "ConfigMap must be applied last so catalog-rendered COGNI_NODE_ENDPOINTS cannot be shadowed by stale Secret keys." >&2
    echo "Actual first=$first_envfrom second=$second_envfrom" >&2
    rc=1
  fi

  if [ "$rc" -ne 0 ]; then
    echo "        Run: bash scripts/ci/render-scheduler-worker-endpoints.sh --write" >&2
    exit 1
  fi
}

write() {
  local endpoints env
  endpoints="$(render)"
  ENDPOINTS="$endpoints" yq -i '.data.COGNI_NODE_ENDPOINTS = strenv(ENDPOINTS)' "$CONFIGMAP_PATH"
  echo "wrote placement-default endpoints → $CONFIGMAP_PATH"
  while read -r env; do
    [ -n "$env" ] || continue
    write_patch "$env"
    echo "wrote ${env} provider-resolved endpoints → $(patch_path "$env")"
  done < <(overlay_envs)
}

case "${1:-}" in
  --check)
    check
    echo "scheduler-worker endpoints are in sync with the catalog."
    ;;
  --write)
    write
    ;;
  --env)
    render_env "${2:?usage: $0 --env <env>}"
    ;;
  "")
    render
    ;;
  *)
    echo "Usage: $0 [--check|--write|--env <env>]" >&2
    exit 2
    ;;
esac
