#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
# SPDX-FileCopyrightText: 2025 Cogni-DAO
#
# render-caddyfile.sh — emit the edge Caddyfile from the catalog (CATALOG_IS_SSOT).
#
# task.5078 — the edge reverse-proxy roster used to be hand-maintained: one
# static site block per node in Caddyfile.tmpl + matching per-node *_DOMAIN /
# *_UPSTREAM vars in deploy-infra.sh and docker-compose.yml. Adding a node (and
# canary proved it) meant editing 3 files in 5+ spots, and the node silently had
# no edge route until someone did. This generator loops NODE_TARGETS instead, so
# a new `type: node` catalog entry (with node_port) yields its edge block for
# free — adding a node is a one-PR, catalog-only change.
#
# Output is the committed infra/compose/edge/configs/Caddyfile.tmpl. Per-node
# host is left as an env var (`{$<SLUG>_DOMAIN}`) because it differs per
# environment (resy-test… / resy-preview… / resy.…); deploy-infra.sh and
# provision-env-vm.sh write those vars to the edge .env via the same NODE_TARGETS
# loop. The upstream port is env-invariant, so it is baked from catalog node_port.
#
# Usage: render-caddyfile.sh            # write canonical template to stdout
#        render-caddyfile.sh --check    # diff stdout against the committed file
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/ci/lib/image-tags.sh
source "${SCRIPT_DIR}/lib/image-tags.sh"

CADDYFILE_PATH="${SCRIPT_DIR}/../../infra/compose/edge/configs/Caddyfile.tmpl"

slug_for_node() { echo "$1" | tr '[:lower:]-' '[:upper:]_'; }

# Emit a reverse-proxy site block. $1=host-expr $2=upstream-expr $3=access-log-file
emit_site_block() {
  local host="$1" upstream="$2" logfile="$3"
  cat <<BLOCK
${host} {
  encode zstd gzip

  @public path /api/v1/public/*
  handle @public {
    reverse_proxy ${upstream} {
      header_up X-Real-IP {remote_host}
      transport http {
        response_header_timeout 10s
      }
    }
  }

  reverse_proxy ${upstream}

  log {
    format json
    output file /data/logs/caddy/${logfile} {
      roll_size 10MB
      roll_keep 7
      roll_keep_for 168h
    }
  }
}
BLOCK
}

render() {
  cat <<'HEADER'
# GENERATED by scripts/ci/render-caddyfile.sh from infra/catalog/*.yaml —
# DO NOT EDIT BY HAND. Add a node = add its catalog entry (with node_port) and
# run `pnpm gen:caddyfile`. CI (`scripts/ci/render-caddyfile.sh --check`) fails
# if this file drifts from the catalog. See docs/guides/create-node.md.
{
  log {
    level INFO
    format json
    output file /data/logs/caddy/caddy.log {
      roll_size 10MB
      roll_keep 7
      roll_keep_for 168h
    }
  }
}

# Redirect www to non-www (canonical operator domain)
www.{$DOMAIN} {
  redir https://{$DOMAIN}{uri} permanent
}
HEADER

  # Primary (operator) first — serves the bare ${DOMAIN}; upstream default
  # stays the docker-DNS `app:3000` for local stacks, overridden to the k3s
  # NodePort by deploy-infra.sh on the VM.
  local node slug port
  for node in "${NODE_TARGETS[@]}"; do
    if is_primary_host "$node"; then
      slug="$(slug_for_node "$node")"
      port="$(node_port_for_target "$node")"
      echo
      echo "# ── ${node} (primary domain) → k3s NodePort ${port} ──────────────────────"
      emit_site_block '{$DOMAIN}' "{\$${slug}_UPSTREAM:app:3000}" "access.log"
    fi
  done

  # Non-primary nodes, deterministic order. Host is env-substituted
  # ({$<SLUG>_DOMAIN}, written to the edge .env per env); upstream port is baked
  # from catalog node_port (env-invariant). A `.localhost` host default keeps
  # the local docker stack's Caddy loadable when the var is unset.
  for node in $(printf '%s\n' "${NODE_TARGETS[@]}" | sort); do
    is_primary_host "$node" && continue
    slug="$(slug_for_node "$node")"
    port="$(node_port_for_target "$node")"
    echo
    echo "# ── ${node} node → k3s NodePort ${port} ──────────────────────────────────"
    emit_site_block \
      "{\$${slug}_DOMAIN:${node}.localhost}" \
      "{\$${slug}_UPSTREAM:host.docker.internal:${port}}" \
      "access-${node}.log"
  done
}

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$CADDYFILE_PATH" <(render); then
    echo "[ERROR] ${CADDYFILE_PATH} is out of sync with infra/catalog/*.yaml." >&2
    echo "        Run: pnpm gen:caddyfile" >&2
    exit 1
  fi
  echo "Caddyfile.tmpl is in sync with the catalog."
else
  render
fi
