// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@features/nodes/repo-spec-builder`
 * Purpose: Build the governance-only `.cogni/repo-spec.yaml` emitted by node formation.
 * Scope: Pure transformer — takes server-verified DAO addresses and emits the YAML that
 *   setup.verify returns and the publish step commits. No IO, no env.
 * Invariants: FORMATION_IS_GOVERNANCE_ONLY — payments remain pending_activation.
 * Side-effects: none
 * Links: docs/spec/node-formation.md, packages/repo-spec, task.5083
 * @public
 */

import { v5 as uuidv5 } from "uuid";

import type { NodeKnowledgeRemote } from "@/shared/node-app-scaffold/knowledge-remote";

export interface NodeRepoSpecInput {
  nodeId: string;
  chainId: number;
  daoAddress: string;
  pluginAddress: string;
  signalAddress: string;
  tokenAddress?: string;
  knowledgeRemote?: NodeKnowledgeRemote;
}

export function buildPendingActivationRepoSpecYaml(
  input: NodeRepoSpecInput
): string {
  const scopeId = uuidv5("default", input.nodeId);
  const tokenLine = input.tokenAddress
    ? `  token_contract: "${input.tokenAddress}"\n`
    : "";

  return `# Generated by Node Formation
# Copy this to .cogni/repo-spec.yaml

schema_version: "0.1.4"

# Unique identity for this node deployment.
# Generated once at init; must never change for an existing deployment.
node_id: "${input.nodeId}"

# Governance domain. Derived from node_id + the default scope key.
scope_id: "${scopeId}"
scope_key: "default"

governance:
  dao_contract: "${input.daoAddress}"
  plugin_contract: "${input.pluginAddress}"
  signal_contract: "${input.signalAddress}"
${tokenLine}  chain_id: "${input.chainId}"
  base_url: "https://proposal.cognidao.org"

${input.knowledgeRemote ? renderKnowledgeBlock(input.knowledgeRemote) : ""}

# Payment rails — activate with: pnpm node:activate-payments
payments:
  status: pending_activation

# Token distributions — activate after verifying DAO-controlled minted inventory.
distributions:
  status: pending_activation
`;
}

function renderKnowledgeBlock(remote: NodeKnowledgeRemote): string {
  return `knowledge:
  database: "${remote.database}"
  remote:
    provider: dolthub
    owner: "${remote.owner}"
    repo: "${remote.repo}"
    url: "${remote.url}"
    custody: cogni-owned
`;
}
