name: toks4
type: node
port: 3200
node_port: 31700
dockerfile: nodes/toks4/app/Dockerfile
image_tag_suffix: "-toks4"
migrator_tag_suffix: "-toks4-migrate"
source_repo: https://github.com/cogni-test-org/test-cog.git
image_repository: ghcr.io/cogni-test-org/test-cog
candidate_a_branch: deploy/candidate-a-toks4
preview_branch: deploy/preview-toks4
production_branch: deploy/production-toks4
envs: [candidate-a]
activity_env: candidate-a
owner_wallet: "0x070075F1389Ae1182aBac722B36CA12285d0c949"
path_prefix: nodes/toks4/
node_id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
