// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/secrets/node-secrets-reserved`
 * Purpose: Gate 2 for node self-serve secret writes — a DENYLIST, not an allowlist.
 *   A node owner (OpenFGA `can_manage_secrets`) owns their ENTIRE namespace
 *   `cogni/<env>/<node>/*` and may set/rotate/ADD any key there — that is the
 *   scope (per-node, not shared). The only keys they may NOT touch are the small,
 *   fixed set the SUBSTRATE generates/derives into that same path (DB creds, DSNs,
 *   identity material); overwriting one would break the node's own DB/sessions.
 * Invariants:
 *   - DENYLIST_NOT_ALLOWLIST: new keys are allowed by default. The security
 *     boundary is OpenFGA per-node + the operator-stamped `cogni/<env>/<node>/*`
 *     path + the OpenBao `_system`/`_shared` policy deny — NOT a per-key list.
 *     This needs no per-node codegen and never blocks a node adding a new key.
 *   - SUBSTRATE_OWNS_DB_CREDS: the reserved set mirrors secrets-management.md
 *     Invariant 15 (DB role material is OpenBao/substrate-owned). Fixed +
 *     operator-domain — independent of any node's catalog.
 * Side-effects: none
 * Links: docs/design/node-self-serve-secrets.md, docs/spec/secrets-management.md
 * @public
 */

/**
 * Substrate-managed keys living in a node's own `cogni/<env>/<node>/*` path.
 * Generated/derived by `secret-materialize` + the DB provisioners — a node owner
 * must not clobber them via self-serve (it would break their node's DB/DSN/auth,
 * or silently corrupt data encrypted under a per-node key).
 *
 * This set must mirror the materializer's `key_is_agent_generated` predicate
 * (`scripts/ci/secret-materialize.sh`: `source: agent` + random `generate.kind`)
 * PLUS the derived DB DSNs. Those keys are minted/derived fresh per node and are
 * declared "NEVER overwritten by a human" at materialize time; allowing a
 * self-serve write of one is the same overwrite by another door. The two
 * expressions of this rule live in different runtimes (bash materializer reads
 * the catalog; this guard ships in an operator image WITHOUT the catalog), so
 * they are kept in sync by hand today. DURABLE FIX: codegen this set from the
 * catalog's agent-generated entries at build time (#1479 typed-module pattern,
 * same as the A2 allowlist) so the two can never drift again. The drift is what
 * let a self-serve write clobber `CONNECTIONS_ENCRYPTION_KEY` on prod beacon.
 */
export const SUBSTRATE_RESERVED_KEYS: ReadonlySet<string> = new Set<string>([
  // Per-node DB role material + DSNs (substrate-owned; secrets-management.md Inv 15).
  "APP_DB_PASSWORD",
  "APP_DB_SERVICE_PASSWORD",
  "APP_DB_READONLY_PASSWORD",
  "DOLTGRES_PASSWORD",
  "DOLTGRES_READER_PASSWORD",
  "DOLTGRES_WRITER_PASSWORD",
  "DATABASE_URL",
  "DATABASE_SERVICE_URL",
  "DOLTGRES_URL",
  "POSTGRES_ROOT_PASSWORD",
  // Per-node agent-minted identity / crypto-at-rest / internal-auth keys.
  // Clobbering any of these breaks sessions, decryption, webhooks, or internal
  // auth for the node — they are generated by the substrate, never set by hand.
  "AUTH_SECRET", // NextAuth session key
  "LITELLM_VIRTUAL_KEY", // Per-node LiteLLM key; materializer owns registration + rotation
  // The private Akash transaction actuator's bearer token (task.5102). It became
  // `source: agent` with a hex generator, so secret-materialize.sh mints and rotates it
  // into `cogni/<env>/akash-tx-actuator`. A self-serve write would clobber the value the
  // Crossplane Composition authenticates with and silently wedge every paid mutation.
  "AKASH_TX_ACTUATOR_TOKEN",
  "CONNECTIONS_ENCRYPTION_KEY", // AES key for BYO-AI connections at rest
  "INTERNAL_OPS_TOKEN", // deploy → governance schedule sync auth
  "METRICS_TOKEN", // Prometheus scrape → /api/metrics auth
  "GH_WEBHOOK_SECRET", // GitHub App webhook HMAC (dual-plane: must byte-match the App)
  "POLY_WALLET_AEAD_KEY_HEX", // poly wallet AEAD key (clobber = wallet decryption loss)
  // Operator-only Ed25519 seed signing every fleet identity attestation. Its
  // public half is published at /.well-known/jwks.json and pinned by every
  // relying node, so a self-serve write does not fail loudly — it silently
  // invalidates every attestation on every node at once (task.5024).
  "IDENTITY_ATTESTATION_PRIVATE_KEY",
]);

/**
 * Gate 2: may a node owner self-serve `key` within their OWN namespace? True for
 * any key EXCEPT the substrate-reserved set. The KEY format is validated upstream
 * (route Zod) and the path is operator-stamped to the authorized node, so this is
 * the only per-key restriction — a footgun guard, not the security boundary.
 */
export function isNodeOwnedSecretKey(key: string): boolean {
  return !SUBSTRATE_RESERVED_KEYS.has(key);
}

/**
 * bug.5016 — the SILENT-REVERT class. Keys declaring `inheritFrom: <owner>` in
 * `infra/secrets-catalog.yaml`, mapped to the node that holds the canonical value.
 *
 * For these `secret-materialize.sh` is OVERWRITE-ON-DRIFT, not preserve-existing: it
 * reads the owner's value and re-seeds the node whenever the two differ (deliberate —
 * the node MUST byte-match the canonical owner, the bug.5021 fix). That branch runs
 * BEFORE the preserve-existing check, so it beats a hand-set value every time. The
 * consequence is the bug: a self-serve write to a NON-owner node returns `200` with a
 * real KV version, and the next flight silently restores the owner's value.
 *
 * This is an OWNER BINDING, not a denylist, and the distinction is load-bearing. Writing
 * `OPENROUTER_API_KEY` at `operator` IS the rotation — it is the canonical source the
 * fan-out reads, and it is the documented clean path in the `openrouter-api-key-expert`
 * skill. Blocking the key outright would break the one write that actually works. Only
 * the non-owner write is refused, because only that one gets reverted.
 *
 * `GH_WEBHOOK_SECRET` also appears in `SUBSTRATE_RESERVED_KEYS` above and is therefore
 * refused everywhere, including at its owner — correct, because it is `source: agent`
 * AND dual-plane (it must byte-match the GitHub App, so a human must never type it).
 */
export const INHERITED_KEY_OWNER: ReadonlyMap<string, string> = new Map<
  string,
  string
>([
  ["LITELLM_MASTER_KEY", "operator"],
  ["SCHEDULER_API_TOKEN", "operator"],
  ["OPENROUTER_API_KEY", "operator"],
  ["EVM_RPC_URL", "operator"],
  ["GH_WEBHOOK_SECRET", "operator"],
]);

/**
 * The node holding the canonical value for `key`, or `undefined` when the key has no
 * `inheritFrom` owner. A write from any other node is accepted-then-reverted, so the
 * route refuses it instead of reporting a success that will not survive the next flight.
 */
export function inheritedKeyOwner(key: string): string | undefined {
  return INHERITED_KEY_OWNER.get(key);
}

/**
 * Gate 3: may a logical secret key cross into an OFF-CLUSTER workload
 * (Akash and friends), where the operator controls neither the host nor the
 * disk? A DENYLIST, keyed on PROVENANCE — never on a node's name.
 *
 * The rule, stated once: a key is denied iff the OPERATOR/SUBSTRATE mints,
 * rotates, or fleet-shares its value. Those credentials authorize action
 * BEYOND the node that would carry them — one exfiltrated copy compromises the
 * fleet, not one tenant — so no CR may ship them off-substrate, even when the
 * CR legitimately declares the logical key.
 *
 * The converse is equally load-bearing: a key whose value the NODE owns —
 * minted for that node, living only at `cogni/<env>/<node>/<KEY>`, blast
 * radius = that node — is ALLOWED BY DEFAULT, however sensitive it is.
 * Custody, wallet, and vendor-API keys are a node's own business; the node/env
 * OpenBao namespace + OpenFGA are the authority, not an operator code list.
 *
 * Invariants:
 *   - PROVENANCE_NOT_NAMES: entries are justified by who mints/owns the value,
 *     not by how scary the key sounds. Shared platform code names no NODE
 *     (bug.5093: name-listing `POLY_*`/`PRIVY_*`/`DISCORD_BOT_TOKEN` here made
 *     poly undeployable to Akash and contradicted this file's own doc comment).
 *     Naming a shared SERVICE the operator owns — `DOLTHUB_*`, `LITELLM_*` — is
 *     NOT a callout: the rule bans enumerating one node's secrets, not
 *     protecting fleet credentials that no node owns or needs.
 *   - DENYLIST_NOT_ALLOWLIST: an unknown key is allowed. Adding an entry
 *     requires naming the operator/fleet/substrate owner of its value.
 */
export const OFF_CLUSTER_WORKLOAD_DENIED_KEYS: ReadonlySet<string> = new Set([
  // Operator control-plane API credentials. The operator mints these against
  // its own vendor accounts; a copy lets the holder drive fleet infrastructure
  // (deploy compute, rewrite DNS, read fleet telemetry) from anywhere.
  // RETIRED NAME (task.5138): the app's Akash Console key slot was removed — one account,
  // one key, held only by the actuator. The name stays denied so no node can ever squat it.
  "AKASH_CONSOLE_API_KEY",
  // Same class, tighter custody: the private Akash transaction actuator is the ONE active
  // writer on the operator sponsor wallet (task.5095, story.5016). It lives in its own
  // `cogni/<env>/akash-tx-actuator` bucket precisely so nothing else can read it; a node
  // workload holding a copy could create paid leases AND break ONE_WALLET_ONE_WRITER.
  "AKASH_ACTUATOR_CONSOLE_API_KEY",
  // The bearer token that unlocks that second wallet over the wire (task.5102). The
  // actuator is a private ClusterIP wallet writer with no other authentication, so a
  // copy on a rented multi-tenant provider is equivalent to holding the key itself.
  "AKASH_TX_ACTUATOR_TOKEN",
  "CLOUDFLARE_API_TOKEN",
  "CLOUDFLARE_ZONE_ID",
  "GH_GRAFANA_PARENT_SA_TOKEN",
  // Fleet-shared AI-gateway credentials (`service: _shared` / operator-owned
  // in infra/secrets-catalog.yaml). ONE value authenticates the whole fleet, so
  // it spends every node's budget. A workload gets the node-scoped
  // `LITELLM_VIRTUAL_KEY` instead — the cogni-node-app-v1 runtime profile
  // renames that virtual key to LITELLM_MASTER_KEY inside the container
  // (compute-workload-reconciler.ts), so the real master key never leaves here.
  "LITELLM_MASTER_KEY",
  "OPENROUTER_API_KEY",
  // Fleet-shared DoltHub credentials (`tier: A1, service: _shared`, same shape
  // as LITELLM_MASTER_KEY above). ONE value is fanned into every node's path by
  // secret-materialize.sh — these are NOT per-node material, so they are not a
  // node-specific callout: DOLTHUB is a shared SERVICE, not a node. The
  // no-callouts rule bans enumerating a particular NODE's secrets; it does not
  // stop the operator protecting its own fleet credentials. No node needs
  // these, so shipping a fleet-wide DoltHub write token to a rented
  // multi-tenant provider is pure blast radius for zero benefit.
  "DOLTHUB_API_TOKEN",
  "DOLT_CREDS_JWK",
  "DOLT_CREDS_KEYID",
  "DOLTHUB_OAUTH_CLIENT_ID",
  "DOLTHUB_OAUTH_CLIENT_SECRET",
  // Fleet identity material. The attestation seed signs EVERY node's identity
  // and its public half is pinned fleet-wide (task.5024); the review App key
  // is one GitHub App installed across every node repo.
  "IDENTITY_ATTESTATION_PRIVATE_KEY",
  "GH_REVIEW_APP_ID",
  "GH_REVIEW_APP_PRIVATE_KEY_BASE64",
  // Substrate-owned database role material (secrets-management.md Invariant 15).
  // Minted by the DB provisioners, not by the node; they authorize direct
  // in-cluster Postgres/Doltgres role login, bypassing the node's app layer.
  // An off-cluster workload reaches its data through its own DSN, not these.
  "APP_DB_PASSWORD",
  "APP_DB_SERVICE_PASSWORD",
  "APP_DB_READONLY_PASSWORD",
  "DOLTGRES_PASSWORD",
  "DOLTGRES_READER_PASSWORD",
  "DOLTGRES_WRITER_PASSWORD",
  "POSTGRES_ROOT_PASSWORD",
  "TEMPORAL_DB_PASSWORD",
  // Supply-chain credentials owned by the operator's CI plane. These write to
  // repos, registries, and Actions — the inputs every node's image is built
  // from — so a leak compromises the fleet upstream of any single node.
  "SSH_DEPLOY_KEY",
  "GHCR_DEPLOY_TOKEN",
  "ACTIONS_AUTOMATION_BOT_PAT",
  "GIT_READ_TOKEN",
]);

const NODE_SECRET_KEY_PATTERN = /^[A-Z_][A-Z0-9_]{0,127}$/;

/**
 * Gate 3: declared key is format-safe and not an operator/fleet/substrate
 * credential. Node-owned keys — including custody and wallet material — pass.
 */
export function isOffClusterWorkloadSecretKey(key: string): boolean {
  return (
    NODE_SECRET_KEY_PATTERN.test(key) &&
    !OFF_CLUSTER_WORKLOAD_DENIED_KEYS.has(key)
  );
}
