// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// SPDX-FileCopyrightText: 2025 Cogni-DAO

/**
 * Module: `@shared/secrets/node-secrets-reserved`
 * Purpose: Gate 2 for node self-serve secret writes — a DENYLIST, not an allowlist.
 *   A node owner (OpenFGA `can_manage_secrets`) owns their ENTIRE namespace
 *   `cogni/<env>/<node>/*` and may set/rotate/ADD any key there — that is the
 *   scope (per-node, not shared). The only keys they may NOT touch are the small,
 *   fixed set the SUBSTRATE generates/derives into that same path (DB creds, DSNs,
 *   identity material); overwriting one would break the node's own DB/sessions.
 * Invariants:
 *   - DENYLIST_NOT_ALLOWLIST: new keys are allowed by default. The security
 *     boundary is OpenFGA per-node + the operator-stamped `cogni/<env>/<node>/*`
 *     path + the OpenBao `_system`/`_shared` policy deny — NOT a per-key list.
 *     This needs no per-node codegen and never blocks a node adding a new key.
 *   - SUBSTRATE_OWNS_DB_CREDS: the reserved set mirrors secrets-management.md
 *     Invariant 15 (DB role material is OpenBao/substrate-owned). Fixed +
 *     operator-domain — independent of any node's catalog.
 * Side-effects: none
 * Links: docs/design/node-self-serve-secrets.md, docs/spec/secrets-management.md
 * @public
 */

/**
 * Substrate-managed keys living in a node's own `cogni/<env>/<node>/*` path.
 * Generated/derived by `secret-materialize` + the DB provisioners — a node owner
 * must not clobber them via self-serve (it would break their node's DB/DSN/auth,
 * or silently corrupt data encrypted under a per-node key).
 *
 * This set must mirror the materializer's `key_is_agent_generated` predicate
 * (`scripts/ci/secret-materialize.sh`: `source: agent` + random `generate.kind`)
 * PLUS the derived DB DSNs. Those keys are minted/derived fresh per node and are
 * declared "NEVER overwritten by a human" at materialize time; allowing a
 * self-serve write of one is the same overwrite by another door. The two
 * expressions of this rule live in different runtimes (bash materializer reads
 * the catalog; this guard ships in an operator image WITHOUT the catalog), so
 * they are kept in sync by hand today. DURABLE FIX: codegen this set from the
 * catalog's agent-generated entries at build time (#1479 typed-module pattern,
 * same as the A2 allowlist) so the two can never drift again. The drift is what
 * let a self-serve write clobber `CONNECTIONS_ENCRYPTION_KEY` on prod beacon.
 */
export const SUBSTRATE_RESERVED_KEYS: ReadonlySet<string> = new Set<string>([
  // Per-node DB role material + DSNs (substrate-owned; secrets-management.md Inv 15).
  "APP_DB_PASSWORD",
  "APP_DB_SERVICE_PASSWORD",
  "APP_DB_READONLY_PASSWORD",
  "DOLTGRES_PASSWORD",
  "DOLTGRES_READER_PASSWORD",
  "DOLTGRES_WRITER_PASSWORD",
  "DATABASE_URL",
  "DATABASE_SERVICE_URL",
  "DOLTGRES_URL",
  "POSTGRES_ROOT_PASSWORD",
  // Per-node agent-minted identity / crypto-at-rest / internal-auth keys.
  // Clobbering any of these breaks sessions, decryption, webhooks, or internal
  // auth for the node — they are generated by the substrate, never set by hand.
  "AUTH_SECRET", // NextAuth session key
  "CONNECTIONS_ENCRYPTION_KEY", // AES key for BYO-AI connections at rest
  "INTERNAL_OPS_TOKEN", // deploy → governance schedule sync auth
  "METRICS_TOKEN", // Prometheus scrape → /api/metrics auth
  "GH_WEBHOOK_SECRET", // GitHub App webhook HMAC (dual-plane: must byte-match the App)
  "POLY_WALLET_AEAD_KEY_HEX", // poly wallet AEAD key (clobber = wallet decryption loss)
]);

/**
 * Gate 2: may a node owner self-serve `key` within their OWN namespace? True for
 * any key EXCEPT the substrate-reserved set. The KEY format is validated upstream
 * (route Zod) and the path is operator-stamped to the authorized node, so this is
 * the only per-key restriction — a footgun guard, not the security boundary.
 */
export function isNodeOwnedSecretKey(key: string): boolean {
  return !SUBSTRATE_RESERVED_KEYS.has(key);
}
