-- Migration: Resync the drizzle snapshot baseline to current reality. NO-OP SQL by design.
--
-- Why this exists: the snapshot chain was frozen at 0029. Hand-written migrations
-- (0030 nodes CHECK, 0031 node_access_requests, 0032 epoch RLS) emit no _snapshot.json,
-- so `drizzle-kit generate` diffed schema TS against the stale 0029 snapshot and emitted
-- destructive drift (DROP TABLE nodes, DROP poly orphans, CREATE an already-existing
-- node_access_requests, DROP POLICY on nodes). This migration ships a fresh, correct
-- 0033_snapshot.json (the true current schema: no poly orphans, node_access_requests +
-- nodes present) so that future `db:generate:operator` produces a clean, minimal diff.
--
-- The SQL is intentionally empty: every DB — fresh (after 0000..0032) and deployed
-- (candidate-a/prod) — is already in this exact state. node_access_requests exists (0031),
-- the nodes CHECK is current (0030). The poly_copy_trade_* orphans physically remain as
-- untracked tables (drizzle ignores DB tables absent from the snapshot); they are NOT
-- dropped here — that is a separate, optional cleanup, kept out of this zero-risk resync.
-- The hand-written nodes `tenant_isolation` RLS policy likewise stays enforced in the DB;
-- drizzle does not model our RLS, so the snapshot omitting it is expected and harmless.
--
-- Enforced going forward by scripts/db/check-generate-clean.mjs (in `pnpm db:check`).
